// tests/conformance/main.cpp -- rx_conformance_render: Phase 5 Stage 1
// Task 11 (#47), gate ruling T11's own glTF PBR conformance harness.
//
// Renders ONE named conformance model (--model <Name>, tests/conformance/
// models.h's own registry) headlessly through RendererX's real
// StandardPBR/Unlit forward path (identical MaterialSystem/GeometryPool/
// TextureCache/rx::ibl bake-chain machinery samples/08_gltf_viewer
// already exercises -- this file adapts that sample's own known-working
// App/makeApp/setupMaterials/buildDrawList/recordSceneDraws shape rather
// than re-deriving it, per this project's own "reuse over reinvention"
// posture applied internally), frames the camera via camera_fit.h's
// ported resetView() algorithm, and gates the captured RGBA8 image
// against a committed Khronos Sample Viewer reference PNG
// (tests/conformance/references/<Name>/reference.png, generated by
// tools/gltf_conformance/generate_reference.mjs -- NEVER regenerated by
// this binary) via samples/common/reference_gate.h's tolerance-gate
// primitive with models.h's own per-model tolerance.
//
// DELIBERATE DIFFERENCES FROM sample08_gltf_viewer (every one load-
// bearing for cross-renderer conformance, not stylistic):
//  - Synchronous rx::asset::Registry::importGltf() (damaged_helmet_test.
//    cpp's own convention) -- no async/loading-state UX needed here.
//  - NO fake directional key light: sample08's own updateDrawDataPerPass
//    Fields() bakes in an improvised `lightColor=(5,5,5)` FG2 stand-in
//    (glTF punctual lights are not consumed until Stage 2/Task 13) --
//    every conformance model this ticket gates is IBL-only content (no
//    KHR_lights_punctual), so carrying that fake light into THIS capture
//    would be a large, systematic, unaccounted divergence against a
//    reference that has no such light at all. This file's own
//    updateDrawDataPerPassFields() zeroes lightColor/lightDirWorld.
//  - NO skybox pass / no visible environment background: the committed
//    references are generated with `renderEnvironmentMap: false`
//    (harness.html's own methodology comment) -- IBL diffuse/specular
//    terms are still fully live (rx::ibl::bakeEnvironment() + Environment
//    Desc, unchanged from sample08's own setupEnvironment()), only the
//    visible cubemap background draw is skipped, matching the reference
//    side exactly.
//  - A NEW linear-clamp "tonemap" pass (shaders/conformance/
//    tonemap_linear.frag.slang) instead of shaders/multipass/tonemap.
//    frag.slang's own Reinhard curve -- see that new shader's own header
//    comment for why: isolates BRDF/lighting/IBL conformance from the
//    orthogonal tonemap-CURVE question (Phase 5 Task 32), which neither
//    renderer would otherwise agree on by construction (Reinhard vs. the
//    Sample Viewer's KHR_PBR_NEUTRAL/ACES/NONE options are different
//    curves; NONE -- the reference side's own choice -- is the one this
//    file's own new shader reproduces bit-for-bit).
//  - Camera is ALWAYS the ported fitCameraToScene() result (camera_fit.h)
//    -- no orbit-drag, no --exposure (pre-exposure stays neutral, 1.0,
//    matching the reference side's own `exposure: 1.0`).
//  - `--perturb-roughness`: this ticket's own required discrimination
//    proof mechanism ("perturb roughness constant -> gate fails") --
//    OVERRIDES every StandardPBR material's own roughnessFactor param to
//    a fixed constant (kPerturbedRoughnessValue, 0.02) after
//    setupMaterials(), before the real draw. Absolute override, not a
//    relative scale/offset -- see overrideFloatMaterialParamIfPresent()'s
//    own header comment for why two relative mechanisms were tried and
//    rejected first (each has its own real "fixed point" content case).
#include <rx_asset/geometry_pool.h>
#include <rx_asset/registry.h>
#include <rx_asset/texture_cache.h>
#include <rx_asset/texture_decode.h>
#include <rx_core/log.h>
#include <rx_graph/executor.h>
#include <rx_graph/render_graph.h>
#include <rx_graph/scene_color.h>
#include <rx_ibl/bake.h>
#include <rx_material/draw_data.h>
#include <rx_material/material_system.h>
#include <rx_material/param_arena_factory.h>
#include <rx_platform/window.h>
#include <rx_rhi_vk/bindless.h>
#include <rx_rhi_vk/buffer.h>
#include <rx_rhi_vk/command.h>
#include <rx_rhi_vk/context.h>
#include <rx_rhi_vk/deletion_queue.h>
#include <rx_rhi_vk/descriptor_arena.h>
#include <rx_rhi_vk/device.h>
#include <rx_rhi_vk/per_frame_storage_buffer.h>
#include <rx_rhi_vk/pipeline_layout.h>
#include <rx_rhi_vk/texture.h>
#include <rx_rhi_vk/upload.h>
#include <rx_scene/camera.h>
#include <rx_scene/scene.h>
#include <rx_shader/compiler.h>
#include <rx_shader/reflection.h>
#include <rx_task/scheduler.h>

#include "camera_fit.h"
#include "models.h"
#include <reference_gate.h>

#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>

#include <SDL3/SDL.h>
#include <volk.h>

#include <algorithm>
#include <array>
#include <charconv>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <memory>
#include <optional>
#include <sstream>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace {

constexpr uint32_t kRenderWidth = 512;
constexpr uint32_t kRenderHeight = 512;
constexpr VkDeviceSize kRenderPixelBytes = static_cast<VkDeviceSize>(kRenderWidth) * kRenderHeight * 4;
constexpr VkFormat kDepthFormat = VK_FORMAT_D32_SFLOAT;
// Explicit, NOT `device->swapchainFormat()` -- see tonemap_linear.frag.
// slang's own header comment: this tool's own tonemap shader does its OWN
// explicit `pow(x, 1/2.2)` sRGB encode, so the backbuffer attachment MUST
// be a plain UNORM format (no hardware sRGB re-encode on write, which
// would double-encode against an _SRGB attachment).
constexpr VkFormat kBackbufferFormat = VK_FORMAT_R8G8B8A8_UNORM;

// Matches harness.html's own `state.renderingParameters.clearColor =
// [0.22, 0.25, 0.29, 1.0]` -- an SRGB-DOMAIN literal (what both sides'
// own tonemap paths ultimately write to their 8-bit backbuffer for an
// untouched background pixel). This tool's own forward pass clears its
// LINEAR HDR target, so the literal must be converted back to linear
// first (pow(c, 2.2)) -- the inverse of tonemap_linear.frag.slang's own
// `pow(clamped, 1/2.2)` -- so that after THIS tool's own tonemap pass
// re-applies that forward encode, the final 8-bit value matches the
// reference's literal exactly (up to encode/decode rounding).
float srgbLiteralToLinear(float c) { return std::pow(c, 2.2F); }
const VkClearColorValue kConformanceClearColor{
    {srgbLiteralToLinear(0.22F), srgbLiteralToLinear(0.25F), srgbLiteralToLinear(0.29F), 1.0F}};

struct Args {
    std::string model;
    bool perturbRoughness = false;
    bool validate = false;
    std::string dumpPath;
};

// [Discrimination proof] The fixed override value --perturb-roughness
// applies to every StandardPBR material's own roughnessFactor param --
// see overrideFloatMaterialParamIfPresent()'s own header comment for why
// this is a plain boolean flag with ONE hardcoded value, not a
// user-supplied number: this tool needs exactly one canonical, always-
// wrong render to prove the gate discriminates, not a general fuzzing
// knob, and a fixed constant sidesteps any "0.0 the sentinel for no
// perturbation" vs. "0.0 a legitimate override value" ambiguity a
// float CLI argument would otherwise carry.
constexpr float kPerturbedRoughnessValue = 0.02F;

std::optional<Args> parseArgs(int argc, char** argv) {
    Args args;
    for (int i = 1; i < argc; ++i) {
        const std::string_view arg = argv[i];
        if (arg == "--model" && i + 1 < argc) {
            args.model = argv[++i];
        } else if (arg == "--validate") {
            args.validate = true;
        } else if (arg == "--perturb-roughness") {
            args.perturbRoughness = true;
        } else if (arg == "--dump" && i + 1 < argc) {
            args.dumpPath = argv[++i];
        } else {
            RX_LOG_ERROR("rx_conformance_render: unrecognized argument '{}'", arg);
            return std::nullopt;
        }
    }
    if (args.model.empty()) {
        RX_LOG_ERROR("rx_conformance_render: --model <Name> is required");
        return std::nullopt;
    }
    return args;
}

// --- Shader compile plumbing [copied verbatim from samples/08_gltf_viewer/
// main.cpp's own identically-named helpers -- see that file's own header
// comment for the "per-sample/per-tool independence, copied not shared"
// convention this project already established] --------------------------
VkShaderModule createShaderModuleFromSpirv(VkDevice device, const std::vector<uint32_t>& code) {
    if (code.empty()) {
        return VK_NULL_HANDLE;
    }
    VkShaderModuleCreateInfo info{};
    info.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    info.codeSize = code.size() * sizeof(uint32_t);
    info.pCode = code.data();
    VkShaderModule module = VK_NULL_HANDLE;
    if (vkCreateShaderModule(device, &info, nullptr, &module) != VK_SUCCESS) {
        return VK_NULL_HANDLE;
    }
    return module;
}

std::optional<std::string> readAndConcatenate(const std::vector<std::string>& paths) {
    std::string combined;
    for (const auto& path : paths) {
        std::ifstream file(path, std::ios::binary);
        if (!file.is_open()) {
            RX_LOG_ERROR("rx_conformance_render: failed to open shader file '{}'", path);
            return std::nullopt;
        }
        std::ostringstream contents;
        contents << file.rdbuf();
        combined += contents.str();
        combined += "\n";
    }
    return combined;
}

struct ReflectedModule {
    rx::shader::CompileResult compileResult;
    rx::shader::ShaderLayoutInfo layoutInfo;
};

std::optional<ReflectedModule> compileAndReflect(rx::shader::Compiler& compiler, const std::string& moduleName,
                                                  const std::vector<std::string>& paths,
                                                  const std::vector<std::string>& entryPoints) {
    auto source = readAndConcatenate(paths);
    if (!source.has_value()) {
        return std::nullopt;
    }
    rx::shader::CompileResult compileResult = compiler.compileFromSource(moduleName, *source, entryPoints);
    if (!compileResult.ok) {
        RX_LOG_ERROR("rx_conformance_render: shader compile failed for module '{}':\n{}", moduleName,
                     compileResult.diagnostics);
        return std::nullopt;
    }
    auto layoutInfo = rx::shader::reflect(compileResult);
    if (!layoutInfo.has_value()) {
        RX_LOG_ERROR("rx_conformance_render: reflect() failed for module '{}'", moduleName);
        return std::nullopt;
    }
    return ReflectedModule{std::move(compileResult), std::move(*layoutInfo)};
}

struct CompiledPass {
    VkShaderModule vertModule = VK_NULL_HANDLE;
    VkShaderModule fragModule = VK_NULL_HANDLE;
    rx::rhi::PipelineLayoutBundle layoutBundle;
    VkPipeline pipeline = VK_NULL_HANDLE;
    uint32_t pushConstantOffset = 0;
    uint32_t pushConstantSize = 0;
    VkShaderStageFlags pushConstantStages = 0;
};

void destroyCompiledPass(VkDevice device, CompiledPass& pass) {
    if (pass.pipeline != VK_NULL_HANDLE) {
        vkDestroyPipeline(device, pass.pipeline, nullptr);
        pass.pipeline = VK_NULL_HANDLE;
    }
    if (pass.fragModule != VK_NULL_HANDLE) {
        vkDestroyShaderModule(device, pass.fragModule, nullptr);
        pass.fragModule = VK_NULL_HANDLE;
    }
    if (pass.vertModule != VK_NULL_HANDLE) {
        vkDestroyShaderModule(device, pass.vertModule, nullptr);
        pass.vertModule = VK_NULL_HANDLE;
    }
    pass.layoutBundle = rx::rhi::PipelineLayoutBundle{};
    pass.pushConstantOffset = 0;
    pass.pushConstantSize = 0;
    pass.pushConstantStages = 0;
}

bool assignShaderModules(VkDevice device, const rx::shader::CompileResult& compileResult, const char* vertEntryName,
                          const char* fragEntryName, CompiledPass& pass) {
    for (const auto& blob : compileResult.entryPointCode) {
        VkShaderModule module = createShaderModuleFromSpirv(device, blob.code);
        if (module == VK_NULL_HANDLE) {
            RX_LOG_ERROR("rx_conformance_render: vkCreateShaderModule failed for entry point '{}'",
                         blob.entryPointName);
            return false;
        }
        if (blob.entryPointName == vertEntryName) {
            pass.vertModule = module;
        } else if (fragEntryName != nullptr && blob.entryPointName == fragEntryName) {
            pass.fragModule = module;
        } else {
            RX_LOG_ERROR("rx_conformance_render: unexpected entry point '{}'", blob.entryPointName);
            vkDestroyShaderModule(device, module, nullptr);
            return false;
        }
    }
    if (pass.vertModule == VK_NULL_HANDLE) {
        RX_LOG_ERROR("rx_conformance_render: missing vertex entry point '{}'", vertEntryName);
        return false;
    }
    if (fragEntryName != nullptr && pass.fragModule == VK_NULL_HANDLE) {
        RX_LOG_ERROR("rx_conformance_render: missing fragment entry point '{}'", fragEntryName);
        return false;
    }
    return true;
}

struct TonemapPushConstants {
    uint32_t hdrTextureIndex;
    uint32_t hdrSamplerIndex;
};

// Builds the LINEAR-CLAMP tonemap pipeline (shaders/multipass/tonemap.
// vert.slang + shaders/conformance/tonemap_linear.frag.slang -- see this
// file's own top comment for why NOT shaders/multipass/tonemap.frag.
// slang). Structurally identical to sample08_gltf_viewer's own
// buildTonemapPipeline() (copied, not shared) except for the two shader
// paths and `kBackbufferFormat` above.
bool buildTonemapPipeline(VkDevice device, rx::shader::Compiler& compiler, VkDescriptorSetLayout bindlessSetLayout,
                          const std::filesystem::path& tonemapVertPath, const std::filesystem::path& tonemapFragPath,
                          CompiledPass& tonemapPass) {
    destroyCompiledPass(device, tonemapPass);

    auto reflected = compileAndReflect(compiler, "ConformanceTonemapModule",
                                        {tonemapVertPath.string(), tonemapFragPath.string()}, {"vsMain", "fsMain"});
    if (!reflected.has_value()) {
        return false;
    }
    if (reflected->layoutInfo.pushRanges.size() != 1 ||
        reflected->layoutInfo.pushRanges[0].size != sizeof(TonemapPushConstants)) {
        RX_LOG_ERROR("rx_conformance_render: tonemap shader reflects an unexpected push-constant shape");
        return false;
    }

    auto layoutBundle = rx::rhi::PipelineLayoutBuilder::build(device, reflected->layoutInfo, bindlessSetLayout);
    if (!layoutBundle.has_value()) {
        RX_LOG_ERROR("rx_conformance_render: PipelineLayoutBuilder::build failed for the tonemap pass");
        return false;
    }
    tonemapPass.layoutBundle = std::move(*layoutBundle);
    tonemapPass.pushConstantOffset = reflected->layoutInfo.pushRanges[0].offset;
    tonemapPass.pushConstantSize = reflected->layoutInfo.pushRanges[0].size;
    tonemapPass.pushConstantStages = reflected->layoutInfo.pushRanges[0].stages;

    if (!assignShaderModules(device, reflected->compileResult, "vsMain", "fsMain", tonemapPass)) {
        destroyCompiledPass(device, tonemapPass);
        return false;
    }

    VkPipelineVertexInputStateCreateInfo vertexInputState{};
    vertexInputState.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;

    VkPipelineInputAssemblyStateCreateInfo inputAssemblyState{};
    inputAssemblyState.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
    inputAssemblyState.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

    VkPipelineViewportStateCreateInfo viewportState{};
    viewportState.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
    viewportState.viewportCount = 1;
    viewportState.scissorCount = 1;

    VkPipelineRasterizationStateCreateInfo rasterizationState{};
    rasterizationState.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
    rasterizationState.polygonMode = VK_POLYGON_MODE_FILL;
    rasterizationState.cullMode = VK_CULL_MODE_NONE;
    rasterizationState.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
    rasterizationState.lineWidth = 1.0F;

    VkPipelineMultisampleStateCreateInfo multisampleState{};
    multisampleState.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
    multisampleState.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

    VkPipelineColorBlendAttachmentState blendAttachment{};
    blendAttachment.blendEnable = VK_FALSE;
    blendAttachment.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT |
                                      VK_COLOR_COMPONENT_A_BIT;
    VkPipelineColorBlendStateCreateInfo colorBlendState{};
    colorBlendState.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
    colorBlendState.attachmentCount = 1;
    colorBlendState.pAttachments = &blendAttachment;

    std::array<VkDynamicState, 2> dynamicStates{VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR};
    VkPipelineDynamicStateCreateInfo dynamicState{};
    dynamicState.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
    dynamicState.dynamicStateCount = static_cast<uint32_t>(dynamicStates.size());
    dynamicState.pDynamicStates = dynamicStates.data();

    VkPipelineRenderingCreateInfo renderingCreateInfo{};
    renderingCreateInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO;
    renderingCreateInfo.colorAttachmentCount = 1;
    renderingCreateInfo.pColorAttachmentFormats = &kBackbufferFormat;

    std::array<VkPipelineShaderStageCreateInfo, 2> stages{};
    stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
    stages[0].module = tonemapPass.vertModule;
    stages[0].pName = "main";
    stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
    stages[1].module = tonemapPass.fragModule;
    stages[1].pName = "main";

    VkGraphicsPipelineCreateInfo pipelineInfo{};
    pipelineInfo.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
    pipelineInfo.pNext = &renderingCreateInfo;
    pipelineInfo.stageCount = static_cast<uint32_t>(stages.size());
    pipelineInfo.pStages = stages.data();
    pipelineInfo.pVertexInputState = &vertexInputState;
    pipelineInfo.pInputAssemblyState = &inputAssemblyState;
    pipelineInfo.pViewportState = &viewportState;
    pipelineInfo.pRasterizationState = &rasterizationState;
    pipelineInfo.pMultisampleState = &multisampleState;
    pipelineInfo.pColorBlendState = &colorBlendState;
    pipelineInfo.pDynamicState = &dynamicState;
    pipelineInfo.layout = tonemapPass.layoutBundle.layout;
    pipelineInfo.renderPass = VK_NULL_HANDLE;
    pipelineInfo.basePipelineIndex = -1;

    if (vkCreateGraphicsPipelines(device, VK_NULL_HANDLE, 1, &pipelineInfo, nullptr, &tonemapPass.pipeline) !=
        VK_SUCCESS) {
        RX_LOG_ERROR("rx_conformance_render: vkCreateGraphicsPipelines failed for the tonemap pass");
        destroyCompiledPass(device, tonemapPass);
        return false;
    }
    return true;
}

// --- Material setup helpers [copied from samples/08_gltf_viewer/main.cpp] --
rx::material::PassSignature forwardPassSignature() {
    rx::material::PassSignature sig;
    sig.colorFormats[0] = rx::graph::kHdrFormat;
    sig.colorCount = 1;
    sig.depthFormat = kDepthFormat;
    sig.samples = VK_SAMPLE_COUNT_1_BIT;
    return sig;
}

struct DrawItem {
    uint32_t blockId = 0;
    uint32_t firstIndex = 0;
    uint32_t indexCount = 0;
    int32_t vertexOffset = 0;
    uint32_t drawDataRow = 0;
    size_t materialBindingIndex = 0;
};

struct MaterialGpuBinding {
    rx::material::MaterialHandle handle;
    std::vector<uint8_t> paramBlob;
    std::optional<rx::rhi::Buffer> paramBuffer;
    VkDescriptorSet paramSet = VK_NULL_HANDLE;
    uint32_t pushOffset = 0;
    uint32_t pushSize = 0;
    VkShaderStageFlags pushStages = 0;
};

template <typename T>
bool setMaterialParam(std::vector<uint8_t>& blob, const std::vector<rx::material::MaterialParamInfo>& params,
                      const char* name, const T& value) {
    for (const auto& p : params) {
        if (p.name == name) {
            if (p.size != sizeof(T)) {
                RX_LOG_ERROR("rx_conformance_render: material param '{}' reflected size {} != sizeof(T) {}", name,
                             p.size, sizeof(T));
                return false;
            }
            std::memcpy(blob.data() + p.offset, &value, sizeof(T));
            return true;
        }
    }
    RX_LOG_ERROR("rx_conformance_render: material param '{}' not found in reflection", name);
    return false;
}

// [Discrimination proof, --perturb-roughness-value] Unlike
// setMaterialParam() above, ABSENCE is not an error here -- Unlit
// materials have no `roughnessFactor` param at all, and that is a
// legitimate, expected case this function must silently no-op for
// (returns false, no log) rather than treating as a setup bug.
//
// ABSOLUTE OVERRIDE (blob := value), NOT relative to whatever the
// material already had -- TWO relative mechanisms were tried first and
// both found INSUFFICIENT, for complementary "fixed point" reasons this
// header comment records rather than silently discarding the finding:
//  (1) MULTIPLICATIVE (current *= factor): MetalRoughSpheres' own
//      roughness=0.0 column (the grid's own mirror-smooth, most-
//      visually-distinctive spheres) is a fixed point under
//      multiplication (`0 * anyFactor == 0`) -- that whole column stayed
//      bit-identical regardless of factor magnitude.
//  (2) ADDITIVE, clamped (current = clamp(current + delta, 0, 1)):
//      MetalRoughSpheres' own single shared material's own
//      `roughnessFactor` is ALREADY at glTF's neutral default (1.0 --
//      the model's real per-sphere roughness VARIATION is baked into
//      `Spheres_MetalRough.png`'s own texture data, `roughnessFactor`
//      is just the spec's multiplier on top of it); clamping at the
//      SAME boundary (1.0) the value already sits AT is *itself* the new
//      fixed point -- reproduced directly this task (0.3/0.5/0.6/0.8
//      delta all produced the IDENTICAL, unperturbed render).
// An absolute override has no such fixed point for any starting value
// materially different from the chosen override (0.02 -- see this
// function's own caller).
bool overrideFloatMaterialParamIfPresent(std::vector<uint8_t>& blob,
                                          const std::vector<rx::material::MaterialParamInfo>& params,
                                          const char* name, float value) {
    for (const auto& p : params) {
        if (p.name == name && p.size == sizeof(float)) {
            std::memcpy(blob.data() + p.offset, &value, sizeof(float));
            return true;
        }
    }
    return false;
}

rx::material::AlphaMode toMaterialAlphaMode(rx::asset::AlphaMode mode) {
    switch (mode) {
        case rx::asset::AlphaMode::Opaque:
            return rx::material::AlphaMode::Opaque;
        case rx::asset::AlphaMode::Mask:
            return rx::material::AlphaMode::Mask;
        case rx::asset::AlphaMode::Blend:
            return rx::material::AlphaMode::Blend;
    }
    return rx::material::AlphaMode::Opaque;
}

uint32_t resolveTextureIndex(rx::asset::TextureCache& textures, const rx::asset::TextureRef& ref,
                              rx::asset::TextureRole role) {
    if (!ref.present) {
        return textures.resolve(textures.fallbackHandle(role)).bindlessIndex;
    }
    return textures.resolve(ref.handle).bindlessIndex;
}

uint32_t resolveSamplerIndex(rx::asset::TextureCache& textures, const rx::asset::TextureRef& ref,
                              uint32_t fallbackIndex) {
    std::optional<uint32_t> index = textures.getOrCreateSamplerBindlessIndex(ref.sampler);
    return index.value_or(fallbackIndex);
}

std::array<float, 4> uvTransformParam(const rx::asset::TextureRef& ref) {
    return {ref.uvOffset.x, ref.uvOffset.y, ref.uvScale.x, ref.uvScale.y};
}

// --- App state [trimmed from samples/08_gltf_viewer's own App -- no
// present/orbit-camera/async-import/skybox fields; see this file's own
// top comment for the full list of deliberate omissions] -----------------
struct App {
    std::optional<rx::platform::Window> window;
    std::optional<rx::rhi::Context> context;
    // Set once in makeApp() (below) and handed to rx::rhi::Device::create()
    // immediately afterward -- NOT independently destroyed by destroyApp():
    // Device::create() takes ownership of the surface it is given
    // unconditionally (device.h's own doc comment on that function) and its
    // destructor (Device::destroyAll(), device.cpp) already calls
    // vkDestroySurfaceKHR on it as part of `app.device.reset()` below. This
    // field stays populated with the same (Device-owned) handle value after
    // that point purely so makeApp()'s own error paths can still read it;
    // an explicit second vkDestroySurfaceKHR call in destroyApp() would be a
    // real double-destroy of this handle, not a fix for a leak -- confirmed
    // empirically (fix-round Finding 3 probe, task-11-report.md): it trips
    // VUID-vkDestroySurfaceKHR-surface-01266 immediately (a live swapchain
    // still references the surface at that point) followed by
    // VUID-vkDestroySurfaceKHR-surface-parameter when Device's own destructor
    // runs against the same, already-destroyed handle. Same pattern as
    // samples/08_gltf_viewer's own identical `App::surface` field.
    VkSurfaceKHR surface = VK_NULL_HANDLE;
    std::optional<rx::rhi::Device> device;
    std::optional<rx::rhi::Allocator> allocator;
    std::optional<rx::rhi::Uploader> uploader;
    std::optional<rx::rhi::BindlessTable> bindless;
    std::optional<rx::rhi::DeletionQueue> deletionQueue;
    std::unique_ptr<rx::material::MaterialSystem> materialSystem;
    std::unique_ptr<rx::asset::GeometryPool> geometryPool;
    std::unique_ptr<rx::asset::TextureCache> textureCache;
    std::unique_ptr<rx::asset::Registry> registry;
    std::unique_ptr<rx::task::Scheduler> scheduler;
    std::unique_ptr<rx::graph::Executor> executor;

    CompiledPass tonemapPass;
    VkSampler defaultSampler = VK_NULL_HANDLE;
    rx::rhi::BindlessHandle defaultSamplerHandle;
    VkImageView lastHdrView = VK_NULL_HANDLE;
    rx::rhi::BindlessHandle hdrHandle;

    std::optional<rx::material::DemandSizedMaterialParamArena> materialParamArena;
    std::vector<MaterialGpuBinding> materialBindings;
    std::unordered_map<uint32_t, size_t> materialHandleToBinding;
    std::vector<DrawItem> draws;
    std::optional<rx::rhi::PerFrameStorageBuffer> drawDataBuffer;
    uint32_t currentFrameSlot = 0;
    std::vector<rx::material::DrawDataGpu> drawDataRows;

    // --- Environment / IBL (no skybox -- see this file's own top comment) --
    std::optional<rx::scene::Scene> scene;
    std::optional<rx::ibl::BakeResult> environment;
    VkSampler envCubeSampler = VK_NULL_HANDLE;
    VkSampler envDfgSampler = VK_NULL_HANDLE;
    rx::rhi::BindlessHandle envBaseCubeHandle;
    rx::rhi::BindlessHandle envIrradianceHandle;
    rx::rhi::BindlessHandle envPrefilteredHandle;
    rx::rhi::BindlessHandle envDfgLutHandle;
    rx::rhi::BindlessHandle envCubeSamplerHandle;
    rx::rhi::BindlessHandle envDfgSamplerHandle;
    float envIntensityPhysical = 1.0F;
};

// [Copied from samples/08_gltf_viewer's own basePathDirectory() idiom]
// The directory the running binary itself lives in (SDL_GetBasePath()) --
// used ONLY for this process's own pipeline-cache file (a build-tree-
// relative, preset-agnostic location); every glTF/shader/reference asset
// this tool reads is resolved via RX_REPO_ROOT_DIR instead (this file's
// own top comment / CMakeLists.txt's own header comment explain why this
// tool, unlike a redistributed sample, reads straight from the source
// tree).
std::filesystem::path basePathDirectory() {
    const char* basePath = SDL_GetBasePath();
    if (basePath == nullptr) {
        RX_LOG_WARN("rx_conformance_render: SDL_GetBasePath failed ({}); using the current directory instead",
                    SDL_GetError());
        return ".";
    }
    return std::filesystem::path(basePath);
}

std::unique_ptr<App> makeApp(bool validate) {
    auto app = std::make_unique<App>();

    auto window = rx::platform::Window::create("rx_conformance_render", static_cast<int>(kRenderWidth),
                                                 static_cast<int>(kRenderHeight), /*visible=*/false);
    if (!window.has_value()) {
        RX_LOG_ERROR("rx_conformance_render: Window::create failed: no display backend available");
        return nullptr;
    }
    auto extensions = window->requiredVulkanInstanceExtensions();
    if (extensions.empty()) {
        RX_LOG_ERROR("rx_conformance_render: video driver reports no Vulkan surface extensions");
        return nullptr;
    }
    auto context = rx::rhi::Context::create(extensions, validate);
    if (!context.has_value()) {
        RX_LOG_ERROR("rx_conformance_render: Context::create failed");
        return nullptr;
    }
    app->window.emplace(std::move(*window));
    app->context.emplace(std::move(*context));

    app->surface = app->window->createVulkanSurface(app->context->instance());
    if (app->surface == VK_NULL_HANDLE) {
        RX_LOG_ERROR("rx_conformance_render: createVulkanSurface failed");
        return nullptr;
    }

    auto device = rx::rhi::Device::create(*app->context, app->surface);
    if (!device.has_value()) {
        RX_LOG_ERROR("rx_conformance_render: Device::create failed");
        return nullptr;
    }
    app->device.emplace(std::move(*device));

    auto allocator = rx::rhi::Allocator::create(*app->context, *app->device);
    if (!allocator.has_value()) {
        RX_LOG_ERROR("rx_conformance_render: Allocator::create failed");
        return nullptr;
    }
    app->allocator.emplace(std::move(*allocator));

    auto uploader = rx::rhi::Uploader::create(*app->allocator, *app->device);
    if (!uploader.has_value()) {
        RX_LOG_ERROR("rx_conformance_render: Uploader::create failed");
        return nullptr;
    }
    app->uploader.emplace(std::move(*uploader));

    rx::rhi::BindlessTable::Capacities capacities{/*sampledImages=*/256, /*samplers=*/16, /*storageBuffers=*/8};
    capacities.comparisonSamplers = 1;
    capacities.cubeImages = 4;
    auto bindless =
        rx::rhi::BindlessTable::create(app->device->physicalDevice(), app->device->device(), capacities);
    if (!bindless.has_value()) {
        RX_LOG_ERROR("rx_conformance_render: BindlessTable::create failed");
        return nullptr;
    }
    app->bindless.emplace(std::move(*bindless));
    app->deletionQueue.emplace();

    const std::filesystem::path sharedShaderDir = std::filesystem::path(RX_REPO_ROOT_DIR) / "shaders" / "material";
    // Pipeline cache lives next to the BINARY (SDL_GetBasePath(), matching
    // samples/08_gltf_viewer's own `basePath / "gltf_viewer_pipeline.cache"`
    // convention) -- NOT under a hardcoded "<repo>/build/" path (which
    // assumed a single, specific preset's own build directory name/layout
    // and would be wrong for any other preset).
    app->materialSystem = rx::material::MaterialSystem::create(
        *app->device, *app->bindless, basePathDirectory() / "rx_conformance_render_pipeline.cache", sharedShaderDir);
    if (app->materialSystem == nullptr) {
        RX_LOG_ERROR("rx_conformance_render: MaterialSystem::create failed");
        return nullptr;
    }

    app->geometryPool = rx::asset::GeometryPool::create(*app->allocator, *app->device, *app->uploader);
    if (app->geometryPool == nullptr) {
        RX_LOG_ERROR("rx_conformance_render: GeometryPool::create failed");
        return nullptr;
    }

    app->textureCache = rx::asset::TextureCache::create(*app->allocator, *app->device, *app->uploader,
                                                          *app->bindless, *app->deletionQueue);
    if (app->textureCache == nullptr) {
        RX_LOG_ERROR("rx_conformance_render: TextureCache::create failed");
        return nullptr;
    }

    app->registry = std::make_unique<rx::asset::Registry>();
    app->scheduler = rx::task::Scheduler::create();
    if (app->scheduler == nullptr) {
        RX_LOG_ERROR("rx_conformance_render: Scheduler::create failed");
        return nullptr;
    }
    app->executor = rx::graph::Executor::create(*app->device, *app->scheduler);
    if (app->executor == nullptr) {
        RX_LOG_ERROR("rx_conformance_render: Executor::create failed");
        return nullptr;
    }

    VkSamplerCreateInfo samplerInfo{};
    samplerInfo.sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
    samplerInfo.magFilter = VK_FILTER_LINEAR;
    samplerInfo.minFilter = VK_FILTER_LINEAR;
    samplerInfo.addressModeU = VK_SAMPLER_ADDRESS_MODE_REPEAT;
    samplerInfo.addressModeV = VK_SAMPLER_ADDRESS_MODE_REPEAT;
    samplerInfo.addressModeW = VK_SAMPLER_ADDRESS_MODE_REPEAT;
    samplerInfo.maxLod = VK_LOD_CLAMP_NONE;
    if (vkCreateSampler(app->device->device(), &samplerInfo, nullptr, &app->defaultSampler) != VK_SUCCESS) {
        RX_LOG_ERROR("rx_conformance_render: vkCreateSampler (default sampler) failed");
        return nullptr;
    }
    app->defaultSamplerHandle = app->bindless->registerSampler(app->defaultSampler);
    if (!app->defaultSamplerHandle.isValid()) {
        RX_LOG_ERROR("rx_conformance_render: BindlessTable::registerSampler (default sampler) failed");
        return nullptr;
    }

    auto compiler = rx::shader::Compiler::create();
    if (!compiler.has_value()) {
        RX_LOG_ERROR("rx_conformance_render: rx::shader::Compiler::create failed");
        return nullptr;
    }
    const std::filesystem::path repoRoot(RX_REPO_ROOT_DIR);
    if (!buildTonemapPipeline(app->device->device(), *compiler, app->bindless->descriptorSetLayout(),
                              repoRoot / "shaders" / "multipass" / "tonemap.vert.slang",
                              repoRoot / "shaders" / "conformance" / "tonemap_linear.frag.slang", app->tonemapPass)) {
        return nullptr;
    }

    app->scene.emplace([](rx::asset::MeshHandle) { return rx::asset::AABB{}; });

    return app;
}

uint32_t materialSpecializationBits(const App& app) {
    return app.scene->hasEnvironment() ? rx::material::kSpecializationEnergyCompensation : 0U;
}

// [Copied from samples/08_gltf_viewer's own loadEquirectHdr()] Loads an
// equirect HDR directly (bypassing TextureCache -- temporary bake input).
std::optional<rx::rhi::Texture2D> loadEquirectHdr(rx::rhi::Device& device, rx::rhi::Allocator& allocator,
                                                    rx::rhi::Uploader& uploader, const std::filesystem::path& path) {
    std::ifstream file(path, std::ios::binary | std::ios::ate);
    if (!file.is_open()) {
        RX_LOG_ERROR("rx_conformance_render: failed to open environment file '{}'", path.string());
        return std::nullopt;
    }
    const std::streamsize fileSize = file.tellg();
    if (fileSize <= 0) {
        RX_LOG_ERROR("rx_conformance_render: environment file '{}' is empty or unreadable", path.string());
        return std::nullopt;
    }
    file.seekg(0, std::ios::beg);
    std::vector<std::byte> bytes(static_cast<size_t>(fileSize));
    if (!file.read(reinterpret_cast<char*>(bytes.data()), fileSize)) {
        RX_LOG_ERROR("rx_conformance_render: failed to read environment file '{}'", path.string());
        return std::nullopt;
    }

    VkPhysicalDeviceProperties props{};
    vkGetPhysicalDeviceProperties(device.physicalDevice(), &props);
    auto isFormatSupported = [&](VkFormat format) {
        VkFormatProperties2 formatProps{};
        formatProps.sType = VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_2;
        vkGetPhysicalDeviceFormatProperties2(device.physicalDevice(), format, &formatProps);
        constexpr VkFormatFeatureFlags kNeeded = VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT | VK_FORMAT_FEATURE_TRANSFER_DST_BIT;
        return (formatProps.formatProperties.optimalTilingFeatures & kNeeded) == kNeeded;
    };
    rx::asset::TextureDecodeResult decoded = rx::asset::decodeTextureForUpload(
        bytes, rx::asset::TextureRole::Environment, props.limits.maxImageDimension2D, isFormatSupported);
    if (decoded.outcome != rx::asset::TextureDecodeResult::Outcome::Ready) {
        RX_LOG_ERROR("rx_conformance_render: failed to decode environment '{}': {}", path.string(),
                     decoded.failureReason);
        return std::nullopt;
    }
    if (decoded.isCube) {
        RX_LOG_ERROR("rx_conformance_render: environment '{}' decoded as a CUBE container -- unsupported here",
                     path.string());
        return std::nullopt;
    }

    auto texture = rx::rhi::Texture2D::createForPresuppliedMips(
        device.physicalDevice(), device.device(), allocator, VkExtent2D{decoded.width, decoded.height},
        decoded.format, VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT,
        static_cast<uint32_t>(decoded.levels.size()));
    if (!texture.has_value()) {
        RX_LOG_ERROR("rx_conformance_render: Texture2D::createForPresuppliedMips failed for environment '{}'",
                     path.string());
        return std::nullopt;
    }

    std::vector<rx::rhi::Uploader::ImageMipLevel> uploadLevels;
    uploadLevels.reserve(decoded.levels.size());
    for (const rx::asset::DecodedTextureLevel& level : decoded.levels) {
        rx::rhi::Uploader::ImageMipLevel entry;
        entry.data = level.bytes.data();
        entry.size = static_cast<VkDeviceSize>(level.bytes.size());
        entry.mipLevel = level.level;
        entry.extent = {level.width, level.height};
        uploadLevels.push_back(entry);
    }
    if (!uploader.uploadImageMips(*texture, uploadLevels)) {
        RX_LOG_ERROR("rx_conformance_render: Uploader::uploadImageMips failed for environment '{}'", path.string());
        return std::nullopt;
    }
    rx::rhi::UploadTicket ticket = uploader.flush();
    uploader.wait(ticket);
    return texture;
}

// [Adapted from samples/08_gltf_viewer's own setupEnvironment() -- the
// skybox-pipeline half is DELETED (this tool never draws a visible
// environment background, see this file's own top comment); everything
// else (bake + bindless registration + EnvironmentDesc) is unchanged.]
bool setupEnvironment(App& app, const std::filesystem::path& hdrPath, const std::filesystem::path& iblShaderDir,
                      float intensity) {
    auto equirect = loadEquirectHdr(*app.device, *app.allocator, *app.uploader, hdrPath);
    if (!equirect.has_value()) {
        return false;
    }

    auto cmdCtx =
        rx::rhi::CommandContext::create(app.device->device(), app.device->graphicsQueue(), app.device->graphicsQueueFamily());
    if (!cmdCtx.has_value()) {
        RX_LOG_ERROR("rx_conformance_render: CommandContext::create failed for the IBL bake");
        return false;
    }

    rx::ibl::BakeParams params;
    rx::ibl::BakeTimings timings;
    auto bakeResult = rx::ibl::bakeEnvironment(*app.device, *app.allocator, *cmdCtx, *app.scheduler, *equirect,
                                                /*sourceIsCube=*/false, iblShaderDir, params, &timings,
                                                "rx_conformance_render");
    if (!bakeResult.has_value()) {
        RX_LOG_ERROR("rx_conformance_render: rx::ibl::bakeEnvironment failed for '{}'", hdrPath.string());
        return false;
    }
    app.environment = std::move(*bakeResult);

    VkSamplerCreateInfo cubeSamplerInfo{};
    cubeSamplerInfo.sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
    cubeSamplerInfo.magFilter = VK_FILTER_LINEAR;
    cubeSamplerInfo.minFilter = VK_FILTER_LINEAR;
    cubeSamplerInfo.mipmapMode = VK_SAMPLER_MIPMAP_MODE_LINEAR;
    cubeSamplerInfo.addressModeU = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
    cubeSamplerInfo.addressModeV = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
    cubeSamplerInfo.addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
    cubeSamplerInfo.minLod = 0.0F;
    cubeSamplerInfo.maxLod = VK_LOD_CLAMP_NONE;
    if (vkCreateSampler(app.device->device(), &cubeSamplerInfo, nullptr, &app.envCubeSampler) != VK_SUCCESS) {
        RX_LOG_ERROR("rx_conformance_render: vkCreateSampler (environment cube sampler) failed");
        return false;
    }
    VkSamplerCreateInfo dfgSamplerInfo = cubeSamplerInfo;
    dfgSamplerInfo.mipmapMode = VK_SAMPLER_MIPMAP_MODE_NEAREST;
    if (vkCreateSampler(app.device->device(), &dfgSamplerInfo, nullptr, &app.envDfgSampler) != VK_SUCCESS) {
        RX_LOG_ERROR("rx_conformance_render: vkCreateSampler (environment DFG sampler) failed");
        return false;
    }

    app.envBaseCubeHandle =
        app.bindless->registerCubeSampledImage(app.environment->baseCubemap.view(), VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
    app.envIrradianceHandle = app.bindless->registerCubeSampledImage(app.environment->irradianceCubemap.view(),
                                                                       VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
    app.envPrefilteredHandle = app.bindless->registerCubeSampledImage(app.environment->prefilteredCubemap.view(),
                                                                        VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
    app.envDfgLutHandle =
        app.bindless->registerSampledImage(app.environment->dfgLut.view(), VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
    app.envCubeSamplerHandle = app.bindless->registerSampler(app.envCubeSampler);
    app.envDfgSamplerHandle = app.bindless->registerSampler(app.envDfgSampler);
    if (!app.envBaseCubeHandle.isValid() || !app.envIrradianceHandle.isValid() ||
        !app.envPrefilteredHandle.isValid() || !app.envDfgLutHandle.isValid() ||
        !app.envCubeSamplerHandle.isValid() || !app.envDfgSamplerHandle.isValid()) {
        RX_LOG_ERROR("rx_conformance_render: bindless registration failed for the baked environment");
        return false;
    }

    rx::scene::EnvironmentDesc envDesc;
    envDesc.baseCubemapIndex = app.envBaseCubeHandle.index();
    envDesc.irradianceCubemapIndex = app.envIrradianceHandle.index();
    envDesc.prefilteredCubemapIndex = app.envPrefilteredHandle.index();
    envDesc.dfgLutIndex = app.envDfgLutHandle.index();
    envDesc.cubeSamplerIndex = app.envCubeSamplerHandle.index();
    envDesc.dfgSamplerIndex = app.envDfgSamplerHandle.index();
    envDesc.maxPrefilteredLod = static_cast<float>(app.environment->prefilteredMipCount) - 1.0F;
    envDesc.intensity = intensity;
    app.scene->setEnvironment(envDesc);
    app.envIntensityPhysical = intensity;
    return true;
}

bool createMaterialParamArena(App& app, uint32_t materialCount) {
    auto arena = rx::material::createDemandSizedMaterialParamArena(app.device->device(), materialCount);
    if (!arena.has_value()) {
        RX_LOG_ERROR("rx_conformance_render: createDemandSizedMaterialParamArena failed for {} material(s)",
                     materialCount);
        return false;
    }
    app.materialParamArena = std::move(*arena);
    return true;
}

void destroyApp(App& app) {
    if (app.device.has_value() && app.device->device() != VK_NULL_HANDLE) {
        vkDeviceWaitIdle(app.device->device());
    }
    for (MaterialGpuBinding& binding : app.materialBindings) {
        binding.paramBuffer.reset();
    }
    if (app.materialParamArena.has_value()) {
        vkDestroyDescriptorSetLayout(app.device->device(), app.materialParamArena->setLayout, nullptr);
    }
    app.materialParamArena.reset();
    if (app.drawDataBuffer.has_value() && app.bindless.has_value()) {
        app.drawDataBuffer->release(*app.bindless);
    }
    app.drawDataBuffer.reset();
    if (app.bindless.has_value()) {
        app.bindless->release(app.envBaseCubeHandle);
        app.bindless->release(app.envIrradianceHandle);
        app.bindless->release(app.envPrefilteredHandle);
        app.bindless->release(app.envDfgLutHandle);
        app.bindless->release(app.envCubeSamplerHandle);
        app.bindless->release(app.envDfgSamplerHandle);
    }
    if (app.envCubeSampler != VK_NULL_HANDLE) {
        vkDestroySampler(app.device->device(), app.envCubeSampler, nullptr);
        app.envCubeSampler = VK_NULL_HANDLE;
    }
    if (app.envDfgSampler != VK_NULL_HANDLE) {
        vkDestroySampler(app.device->device(), app.envDfgSampler, nullptr);
        app.envDfgSampler = VK_NULL_HANDLE;
    }
    app.environment.reset();
    destroyCompiledPass(app.device->device(), app.tonemapPass);
    if (app.defaultSamplerHandle.isValid() && app.bindless.has_value()) {
        app.bindless->release(app.defaultSamplerHandle);
    }
    if (app.defaultSampler != VK_NULL_HANDLE) {
        vkDestroySampler(app.device->device(), app.defaultSampler, nullptr);
        app.defaultSampler = VK_NULL_HANDLE;
    }
    app.registry.reset();
    app.textureCache.reset();
    app.geometryPool.reset();
    app.materialSystem.reset();
    app.executor.reset();
    app.scheduler.reset();
    app.deletionQueue.reset();
    app.bindless.reset();
    app.uploader.reset();
    app.allocator.reset();
    // This also destroys `app.surface` (Device::destroyAll(), device.cpp) --
    // see the App::surface field's own comment above for why no separate
    // vkDestroySurfaceKHR call belongs in this function.
    app.device.reset();
}

// [Adapted from samples/08_gltf_viewer's own setupMaterials() -- unchanged
// except for the log-message prefix.] `perturbRoughness` (default false)
// is applied HERE, once, right after each StandardPBR binding's own
// roughnessFactor is written -- see overrideFloatMaterialParamIfPresent()'s
// own header comment for why an ABSENT param (Unlit materials) is not an
// error, and for why this is an absolute override, not a relative
// scale/offset.
bool setupMaterials(App& app, const rx::asset::Registry& registry,
                     const std::vector<rx::asset::MaterialHandle>& materialHandles, bool perturbRoughness) {
    const std::filesystem::path repoRoot(RX_REPO_ROOT_DIR);
    const std::filesystem::path standardPbrPath = repoRoot / "shaders" / "material" / "standard_pbr.slang";
    const std::filesystem::path unlitPath = repoRoot / "shaders" / "material" / "unlit.slang";
    const rx::material::PassSignature passSig = forwardPassSignature();

    for (rx::asset::MaterialHandle assetHandle : materialHandles) {
        const rx::asset::MaterialAsset& asset = registry.material(assetHandle);
        const bool isUnlit = asset.disposition == rx::asset::MaterialDisposition::Unlit;

        rx::material::MaterialFixedFunctionState fixedFunctionState;
        fixedFunctionState.alphaMode = toMaterialAlphaMode(asset.alphaMode);
        fixedFunctionState.doubleSided = asset.doubleSided;

        const std::filesystem::path& modulePath = isUnlit ? unlitPath : standardPbrPath;

        MaterialGpuBinding binding;
        try {
            binding.handle = app.materialSystem->loadMaterial(modulePath, fixedFunctionState);
        } catch (const std::exception& ex) {
            RX_LOG_ERROR("rx_conformance_render: loadMaterial('{}') failed for material '{}': {}",
                         modulePath.string(), asset.name, ex.what());
            return false;
        }

        const uint32_t blockSize = app.materialSystem->paramBlockSize(binding.handle);
        binding.paramBlob.assign(blockSize, uint8_t{0});
        const std::vector<rx::material::MaterialParamInfo> params = app.materialSystem->materialParams(binding.handle);

        const float appliedAlphaCutoff = asset.alphaMode == rx::asset::AlphaMode::Mask ? asset.alphaCutoff : 0.0F;
        const std::array<float, 4> baseColorFactor{asset.baseColorFactor.x, asset.baseColorFactor.y,
                                                     asset.baseColorFactor.z, asset.baseColorFactor.w};

        bool ok = true;
        if (isUnlit) {
            ok = ok && setMaterialParam(binding.paramBlob, params, "baseColorFactor", baseColorFactor);
            ok = ok && setMaterialParam(binding.paramBlob, params, "baseColorTexture",
                                        resolveTextureIndex(*app.textureCache, asset.baseColorTexture,
                                                              rx::asset::TextureRole::BaseColor));
            ok = ok && setMaterialParam(binding.paramBlob, params, "baseColorSampler",
                                        resolveSamplerIndex(*app.textureCache, asset.baseColorTexture,
                                                              app.defaultSamplerHandle.index()));
            ok = ok && setMaterialParam(binding.paramBlob, params, "alphaCutoff", appliedAlphaCutoff);
            ok = ok && setMaterialParam(binding.paramBlob, params, "baseColorUvOffsetScale",
                                        uvTransformParam(asset.baseColorTexture));
        } else {
            const std::array<float, 4> emissiveFactorAndPad{asset.emissiveFactor.x * asset.emissiveStrength,
                                                               asset.emissiveFactor.y * asset.emissiveStrength,
                                                               asset.emissiveFactor.z * asset.emissiveStrength, 0.0F};
            ok = ok && setMaterialParam(binding.paramBlob, params, "baseColorFactor", baseColorFactor);
            ok = ok && setMaterialParam(binding.paramBlob, params, "metallicFactor", asset.metallicFactor);
            ok = ok && setMaterialParam(binding.paramBlob, params, "roughnessFactor", asset.roughnessFactor);
            ok = ok && setMaterialParam(binding.paramBlob, params, "normalScale", asset.normalScale);
            ok = ok && setMaterialParam(binding.paramBlob, params, "occlusionStrength", asset.occlusionStrength);
            ok = ok && setMaterialParam(binding.paramBlob, params, "alphaCutoff", appliedAlphaCutoff);
            ok = ok && setMaterialParam(binding.paramBlob, params, "ior", 1.5F);
            ok = ok && setMaterialParam(binding.paramBlob, params, "specularFactor", 1.0F);
            ok = ok && setMaterialParam(binding.paramBlob, params, "specularColorFactorAndPad",
                                        std::array<float, 4>{1.0F, 1.0F, 1.0F, 0.0F});
            ok = ok && setMaterialParam(binding.paramBlob, params, "dfgY", 1.0F);
            ok = ok && setMaterialParam(binding.paramBlob, params, "emissiveFactorAndPad", emissiveFactorAndPad);
            ok = ok && setMaterialParam(binding.paramBlob, params, "baseColorTexture",
                                        resolveTextureIndex(*app.textureCache, asset.baseColorTexture,
                                                              rx::asset::TextureRole::BaseColor));
            ok = ok && setMaterialParam(binding.paramBlob, params, "metallicRoughnessTexture",
                                        resolveTextureIndex(*app.textureCache, asset.metallicRoughnessTexture,
                                                              rx::asset::TextureRole::MetallicRoughness));
            ok = ok && setMaterialParam(binding.paramBlob, params, "normalTexture",
                                        resolveTextureIndex(*app.textureCache, asset.normalTexture,
                                                              rx::asset::TextureRole::Normal));
            ok = ok && setMaterialParam(binding.paramBlob, params, "occlusionTexture",
                                        resolveTextureIndex(*app.textureCache, asset.occlusionTexture,
                                                              rx::asset::TextureRole::Occlusion));
            ok = ok && setMaterialParam(binding.paramBlob, params, "emissiveTexture",
                                        resolveTextureIndex(*app.textureCache, asset.emissiveTexture,
                                                              rx::asset::TextureRole::Emissive));
            ok = ok && setMaterialParam(binding.paramBlob, params, "baseColorSampler",
                                        resolveSamplerIndex(*app.textureCache, asset.baseColorTexture,
                                                              app.defaultSamplerHandle.index()));
            ok = ok && setMaterialParam(binding.paramBlob, params, "metallicRoughnessSampler",
                                        resolveSamplerIndex(*app.textureCache, asset.metallicRoughnessTexture,
                                                              app.defaultSamplerHandle.index()));
            ok = ok && setMaterialParam(binding.paramBlob, params, "normalSampler",
                                        resolveSamplerIndex(*app.textureCache, asset.normalTexture,
                                                              app.defaultSamplerHandle.index()));
            ok = ok && setMaterialParam(binding.paramBlob, params, "occlusionSampler",
                                        resolveSamplerIndex(*app.textureCache, asset.occlusionTexture,
                                                              app.defaultSamplerHandle.index()));
            ok = ok && setMaterialParam(binding.paramBlob, params, "emissiveSampler",
                                        resolveSamplerIndex(*app.textureCache, asset.emissiveTexture,
                                                              app.defaultSamplerHandle.index()));
            ok = ok && setMaterialParam(binding.paramBlob, params, "baseColorUvOffsetScale",
                                        uvTransformParam(asset.baseColorTexture));
            ok = ok && setMaterialParam(binding.paramBlob, params, "metallicRoughnessUvOffsetScale",
                                        uvTransformParam(asset.metallicRoughnessTexture));
            ok = ok && setMaterialParam(binding.paramBlob, params, "normalUvOffsetScale",
                                        uvTransformParam(asset.normalTexture));
            ok = ok && setMaterialParam(binding.paramBlob, params, "occlusionUvOffsetScale",
                                        uvTransformParam(asset.occlusionTexture));
            ok = ok && setMaterialParam(binding.paramBlob, params, "emissiveUvOffsetScale",
                                        uvTransformParam(asset.emissiveTexture));

            if (perturbRoughness) {
                overrideFloatMaterialParamIfPresent(binding.paramBlob, params, "roughnessFactor",
                                                     kPerturbedRoughnessValue);
            }
        }
        if (!ok) {
            RX_LOG_ERROR("rx_conformance_render: material param setup failed for material '{}'", asset.name);
            return false;
        }

        const rx::shader::ShaderLayoutInfo& layout = app.materialSystem->layoutInfo(binding.handle);
        if (layout.pushRanges.empty()) {
            RX_LOG_ERROR("rx_conformance_render: material '{}' reflects no RxMaterialGlobals push-constant range",
                         asset.name);
            return false;
        }
        binding.pushOffset = layout.pushRanges[0].offset;
        binding.pushSize = layout.pushRanges[0].size;
        binding.pushStages = layout.pushRanges[0].stages;

        auto paramBuffer = app.allocator->createHostVisibleBuffer(blockSize, VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT,
                                                                     rx::rhi::MemoryCategory::Internal);
        if (!paramBuffer.has_value()) {
            RX_LOG_ERROR("rx_conformance_render: createHostVisibleBuffer (material params) failed for material '{}'",
                         asset.name);
            return false;
        }
        std::memcpy(paramBuffer->mappedData(), binding.paramBlob.data(), blockSize);
        paramBuffer->flush();

        VkDescriptorSet paramSet =
            app.materialParamArena->arena.allocate(app.materialParamArena->setLayout, /*uniformBufferDescriptorCount=*/1);
        if (paramSet == VK_NULL_HANDLE) {
            RX_LOG_ERROR("rx_conformance_render: material-params descriptor arena allocation failed for material '{}'",
                         asset.name);
            return false;
        }
        VkDescriptorBufferInfo bufferInfo{paramBuffer->handle(), 0, blockSize};
        VkWriteDescriptorSet write{};
        write.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        write.dstSet = paramSet;
        write.dstBinding = 0;
        write.descriptorCount = 1;
        write.descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
        write.pBufferInfo = &bufferInfo;
        vkUpdateDescriptorSets(app.device->device(), 1, &write, 0, nullptr);

        binding.paramBuffer = std::move(paramBuffer);
        binding.paramSet = paramSet;

        try {
            app.materialSystem->getPipeline({binding.handle, passSig, materialSpecializationBits(app)});
        } catch (const std::exception& ex) {
            RX_LOG_ERROR("rx_conformance_render: D27 pipeline pre-resolution failed for material '{}': {}",
                         asset.name, ex.what());
            return false;
        }

        app.materialHandleToBinding[assetHandle.index()] = app.materialBindings.size();
        app.materialBindings.push_back(std::move(binding));
    }
    return true;
}

// [Adapted from samples/08_gltf_viewer's own buildDrawList() -- the
// TIGHT world-bounds accumulation that sample's own frameCameraToScene()
// used to consume is DELETED here: this tool's own camera fit reads
// accumulateReferenceStyleSceneExtents()'s sphere-cube-unioned output
// instead (main()'s own comment, right before its fitCameraToScene()
// call) -- a plain tight union would NOT match the reference renderer's
// own camera, see camera_fit.h's own header comment.]
bool buildDrawList(App& app, const rx::asset::Registry& registry, const rx::asset::ImportedScene& scene) {
    app.draws.clear();
    app.drawDataRows.clear();

    for (const rx::asset::InstanceRecord& instance : scene.instances) {
        const rx::asset::MeshAsset& mesh = registry.mesh(instance.mesh);
        const glm::mat3 normalMat3 = glm::transpose(glm::inverse(glm::mat3(instance.worldTransform)));
        const glm::mat4 modelTransposed = glm::transpose(instance.worldTransform);
        const glm::mat4 normalMatrixTransposed = glm::transpose(glm::mat4(normalMat3));

        for (const rx::asset::Submesh& submesh : mesh.submeshes) {
            auto it = app.materialHandleToBinding.find(submesh.material.index());
            if (it == app.materialHandleToBinding.end()) {
                // [glTF spec, Mesh Primitive: "material" is OPTIONAL --
                // "When not defined, the primitive uses the DEFAULT
                // material"] Reproduced directly this task:
                // MetalRoughSpheresNoTextures' own "Metal"/"Non-metal"/
                // "Smooth"/"Rough" text-LABEL primitives carry no
                // `material` index at all (verified against the raw glTF
                // JSON) -- import_gltf.cpp's own fillRef()-style
                // resolution gives such a submesh the Registry's own D24/
                // D11 residency-tolerant FALLBACK MaterialHandle, which
                // was never one of `result.materials` (setupMaterials()'s
                // own caller only iterates THAT list), so it never got a
                // binding up front. Lazily bind it here, on first
                // encounter, via the SAME setupMaterials() -- a single-
                // element call is exactly what that function already
                // supports (it operates on any MaterialHandle vector, not
                // specifically `result.materials`); `registry.material()`
                // resolves the fallback handle to a real, valid (if
                // visually neutral) MaterialAsset (D24's own contract),
                // never null. Memoized: only the FIRST submesh referencing
                // this exact fallback handle pays the loadMaterial() cost.
                if (!setupMaterials(app, registry, {submesh.material}, /*perturbRoughness=*/false)) {
                    RX_LOG_ERROR(
                        "rx_conformance_render: on-demand fallback-material binding failed for a submesh with no "
                        "glTF-declared material");
                    return false;
                }
                it = app.materialHandleToBinding.find(submesh.material.index());
                if (it == app.materialHandleToBinding.end()) {
                    RX_LOG_ERROR("rx_conformance_render: submesh references a material with no MaterialGpuBinding");
                    return false;
                }
            }

            DrawItem draw;
            draw.blockId = submesh.range.blockId;
            draw.firstIndex = submesh.range.firstIndex;
            draw.indexCount = submesh.range.indexCount;
            draw.vertexOffset = submesh.range.vertexOffset;
            draw.drawDataRow = static_cast<uint32_t>(app.drawDataRows.size());
            draw.materialBindingIndex = it->second;

            rx::material::DrawDataGpu row;
            row.model = modelTransposed;
            row.normalMatrix = normalMatrixTransposed;
            row.materialIndex = static_cast<uint32_t>(it->second);
            app.drawDataRows.push_back(row);
            app.draws.push_back(draw);
        }
    }

    if (app.draws.empty()) {
        RX_LOG_ERROR("rx_conformance_render: imported scene produced zero draws");
        return false;
    }

    const VkDeviceSize bytes = static_cast<VkDeviceSize>(app.drawDataRows.size()) * sizeof(rx::material::DrawDataGpu);
    auto drawDataBuffer =
        rx::rhi::PerFrameStorageBuffer::create(*app.allocator, *app.bindless, bytes, app.drawDataRows.data());
    if (!drawDataBuffer.has_value()) {
        RX_LOG_ERROR("rx_conformance_render: PerFrameStorageBuffer::create (draw data, {} rows) failed",
                     app.drawDataRows.size());
        return false;
    }
    app.drawDataBuffer = std::move(*drawDataBuffer);
    return true;
}

// [OWN, NOT copied from sample08 -- see this file's own top comment: NO
// fake key light, no skybox row.] IBL environment fields are still fully
// populated exactly like sample08's own equivalent.
void updateDrawDataPerPassFields(App& app, const glm::mat4& viewProj, const glm::vec3& cameraPosWorld) {
    const bool hasEnvironment = app.scene->hasEnvironment();
    rx::scene::EnvironmentDesc envDesc;
    if (hasEnvironment) {
        envDesc = app.scene->environment();
    }

    const glm::mat4 viewProjTransposed = glm::transpose(viewProj);
    for (rx::material::DrawDataGpu& row : app.drawDataRows) {
        row.viewProj = viewProjTransposed;
        row.lightDirWorld = glm::vec4(0.0F, 1.0F, 0.0F, 0.0F);
        row.lightColor = glm::vec4(0.0F, 0.0F, 0.0F, 0.0F);  // NO fake key light -- see this file's own top comment.
        row.ambientColor = glm::vec4(0.0F, 0.0F, 0.0F, 0.0F);
        row.cameraPosWorld = glm::vec4(cameraPosWorld, 0.0F);
        if (hasEnvironment) {
            row.envIrradianceCubeIndex = envDesc.irradianceCubemapIndex;
            row.envPrefilteredCubeIndex = envDesc.prefilteredCubemapIndex;
            row.envDfgLutIndex = envDesc.dfgLutIndex;
            row.envCubeSamplerIndex = envDesc.cubeSamplerIndex;
            row.envDfgSamplerIndex = envDesc.dfgSamplerIndex;
            row.envMaxPrefilteredLod = envDesc.maxPrefilteredLod;
            row.envIntensity = app.envIntensityPhysical;  // exposure stays neutral (1.0) -- see this file's own top comment.
        } else {
            row.envIrradianceCubeIndex = 0xFFFFFFFFu;
            row.envPrefilteredCubeIndex = 0xFFFFFFFFu;
            row.envDfgLutIndex = 0xFFFFFFFFu;
        }
    }
    const VkDeviceSize bytes = static_cast<VkDeviceSize>(app.drawDataRows.size()) * sizeof(rx::material::DrawDataGpu);
    app.drawDataBuffer->write(app.currentFrameSlot, app.drawDataRows.data(), bytes);
}

void recordSceneDraws(VkCommandBuffer cmd, App& app) {
    VkDescriptorSet bindlessSet = app.bindless->descriptorSet();
    VkPipelineLayout anyLayout = app.materialSystem->pipelineLayout(app.materialBindings.front().handle);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, anyLayout, /*firstSet=*/0, 1, &bindlessSet, 0,
                             nullptr);

    const rx::material::PassSignature passSig = forwardPassSignature();
    rx::material::MaterialHandle lastPipelineMaterial;
    uint32_t lastBoundBlock = UINT32_MAX;

    for (const DrawItem& draw : app.draws) {
        MaterialGpuBinding& material = app.materialBindings[draw.materialBindingIndex];

        if (!(material.handle == lastPipelineMaterial)) {
            VkPipeline pipeline =
                app.materialSystem->getPipeline({material.handle, passSig, materialSpecializationBits(app)});
            VkPipelineLayout layout = app.materialSystem->pipelineLayout(material.handle);
            vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline);

            rx::material::MaterialGlobalsPush push;
            push.defaultSamplerIndex = app.defaultSamplerHandle.index();
            push.drawDataBufferIndex = app.drawDataBuffer->bindlessIndex(app.currentFrameSlot);
            vkCmdPushConstants(cmd, layout, material.pushStages, material.pushOffset, material.pushSize, &push);

            vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, layout, /*firstSet=*/1, 1,
                                     &material.paramSet, 0, nullptr);

            lastPipelineMaterial = material.handle;
        }

        if (draw.blockId != lastBoundBlock) {
            app.geometryPool->bind(cmd, draw.blockId);
            lastBoundBlock = draw.blockId;
        }

        vkCmdDrawIndexed(cmd, draw.indexCount, /*instanceCount=*/1, draw.firstIndex, draw.vertexOffset,
                         /*firstInstance=*/draw.drawDataRow);
    }
}

// [OWN -- no sceneReady/loading-state branch (always ready by the time
// this runs) and no skybox call.] Clears to the SAME matched literal
// harness.html's own state.renderingParameters.clearColor uses (see
// kConformanceClearColor's own comment) before drawing.
void recordForward(rx::graph::PassContext& ctx, App& app) {
    VkClearAttachment clearAttachment{};
    clearAttachment.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
    clearAttachment.colorAttachment = 0;
    clearAttachment.clearValue.color = kConformanceClearColor;
    VkClearRect clearRect{};
    clearRect.rect = VkRect2D{{0, 0}, ctx.renderArea};
    clearRect.layerCount = 1;
    vkCmdClearAttachments(ctx.cmd, 1, &clearAttachment, 1, &clearRect);

    VkViewport viewport{0.0F, 0.0F, static_cast<float>(ctx.renderArea.width),
                        static_cast<float>(ctx.renderArea.height), 0.0F, 1.0F};
    VkRect2D scissor{{0, 0}, ctx.renderArea};
    vkCmdSetViewport(ctx.cmd, 0, 1, &viewport);
    vkCmdSetScissor(ctx.cmd, 0, 1, &scissor);

    recordSceneDraws(ctx.cmd, app);
}

void recordTonemapDraw(rx::graph::PassContext& ctx, App& app) {
    VkImageView hdrView = ctx.imageView("hdr");
    if (hdrView != app.lastHdrView) {
        if (app.hdrHandle.isValid()) {
            app.bindless->release(app.hdrHandle);
        }
        app.hdrHandle = app.bindless->registerSampledImage(hdrView, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
        app.lastHdrView = hdrView;
    }

    vkCmdBindPipeline(ctx.cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, app.tonemapPass.pipeline);
    VkDescriptorSet set = app.bindless->descriptorSet();
    vkCmdBindDescriptorSets(ctx.cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, app.tonemapPass.layoutBundle.layout, 0, 1,
                             &set, 0, nullptr);

    VkViewport viewport{0.0F, 0.0F, static_cast<float>(ctx.renderArea.width),
                        static_cast<float>(ctx.renderArea.height), 0.0F, 1.0F};
    VkRect2D scissor{{0, 0}, ctx.renderArea};
    vkCmdSetViewport(ctx.cmd, 0, 1, &viewport);
    vkCmdSetScissor(ctx.cmd, 0, 1, &scissor);

    TonemapPushConstants push{};
    push.hdrTextureIndex = app.hdrHandle.index();
    push.hdrSamplerIndex = app.defaultSamplerHandle.index();
    vkCmdPushConstants(ctx.cmd, app.tonemapPass.layoutBundle.layout, app.tonemapPass.pushConstantStages,
                       app.tonemapPass.pushConstantOffset, app.tonemapPass.pushConstantSize, &push);

    vkCmdDraw(ctx.cmd, 3, 1, 0, 0);
}

rx::graph::AttachmentDesc swapchainRelativeDesc(VkFormat format) {
    rx::graph::AttachmentDesc desc;
    desc.format = format;
    desc.sizeClass = rx::graph::SizeClass::SwapchainRelative;
    desc.width = 1.0F;
    desc.height = 1.0F;
    return desc;
}

rx::graph::AttachmentDesc swapchainRelativeReversedDepthDesc(VkFormat format) {
    rx::graph::AttachmentDesc desc = swapchainRelativeDesc(format);
    desc.depthConvention = rx::graph::DepthConvention::Reversed;
    return desc;
}

void declareGraph(rx::graph::RenderGraph& graph, App& app) {
    graph.addPass("forward")
        .addColorOutput("hdr", swapchainRelativeDesc(rx::graph::kHdrFormat))
        .setDepthStencilOutput("depth", swapchainRelativeReversedDepthDesc(kDepthFormat))
        .setExecute([&app](rx::graph::PassContext& ctx) { recordForward(ctx, app); });

    graph.addPass("tonemap")
        .addTextureInput("hdr")
        .addColorOutput("backbuffer", swapchainRelativeDesc(kBackbufferFormat))
        .setExecute([&app](rx::graph::PassContext& ctx) { recordTonemapDraw(ctx, app); });

    graph.setBackbufferSource("backbuffer");
}

struct ChannelIndices {
    int r;
    int g;
    int b;
};

std::optional<ChannelIndices> channelIndicesForFormat(VkFormat format) {
    switch (format) {
        case VK_FORMAT_R8G8B8A8_UNORM:
        case VK_FORMAT_R8G8B8A8_SRGB:
            return ChannelIndices{0, 1, 2};
        case VK_FORMAT_B8G8R8A8_UNORM:
        case VK_FORMAT_B8G8R8A8_SRGB:
            return ChannelIndices{2, 1, 0};
        default:
            return std::nullopt;
    }
}

bool canonicalizeToRgba8(std::vector<uint8_t>& pixels, VkFormat format) {
    const auto channels = channelIndicesForFormat(format);
    if (!channels.has_value()) {
        RX_LOG_ERROR("rx_conformance_render: backbuffer format {} is not R8G8B8A8/B8G8R8A8", static_cast<int>(format));
        return false;
    }
    if (channels->r == 0 && channels->b == 2) {
        return true;
    }
    for (size_t offset = 0; offset + 4 <= pixels.size(); offset += 4) {
        std::swap(pixels[offset + 0], pixels[offset + 2]);
    }
    return true;
}

}  // namespace

int main(int argc, char** argv) {
    auto args = parseArgs(argc, argv);
    if (!args.has_value()) {
        return 1;
    }

    const rx::conformance::ConformanceModel* model = rx::conformance::findConformanceModel(args->model);
    if (model == nullptr) {
        RX_LOG_ERROR("rx_conformance_render: unknown --model '{}' (see tests/conformance/models.h)", args->model);
        return 1;
    }

    const std::filesystem::path repoRoot(RX_REPO_ROOT_DIR);
    const std::filesystem::path scenePath =
        repoRoot / "assets" / "fetched" / model->name / "glTF" / (model->name + ".gltf");
    const std::filesystem::path referencePath = repoRoot / "tests" / "conformance" / "references" / model->name / "reference.png";
    const std::filesystem::path envPath = repoRoot / "samples" / "08_gltf_viewer" / "environments" / "gate_test_env.hdr";

    if (!std::filesystem::exists(scenePath) || !std::filesystem::exists(referencePath)) {
        if (model->optional) {
            RX_LOG_INFO(
                "rx_conformance_render: '{}' not fetched/referenced locally (optional model -- run "
                "tools/fetch_assets.sh --environment-test and tools/gltf_conformance/generate_reference.mjs "
                "{} to exercise it) -- skipping",
                model->name, model->name);
            return 0;
        }
        RX_LOG_ERROR("rx_conformance_render: '{}' or '{}' not found -- run tools/fetch_assets.sh first",
                     scenePath.string(), referencePath.string());
        return 1;
    }

    auto app = makeApp(args->validate);
    if (app == nullptr) {
        return 1;
    }

    const std::filesystem::path iblShaderDir = repoRoot / "shaders" / "ibl";
    if (!setupEnvironment(*app, envPath, iblShaderDir, /*intensity=*/1.0F)) {
        RX_LOG_ERROR("rx_conformance_render: setupEnvironment failed");
        destroyApp(*app);
        return 1;
    }

    rx::task::Scheduler& scheduler = *app->scheduler;
    rx::asset::ImportResult result =
        app->registry->importGltf(scenePath, *app->geometryPool, scheduler, app->textureCache.get());
    if (!result.ok()) {
        RX_LOG_ERROR("rx_conformance_render: import of '{}' failed: {}", scenePath.string(),
                     rx::asset::importErrorName(result.error));
        destroyApp(*app);
        return 1;
    }

    // +1: headroom for the on-demand D11/D24 FALLBACK material binding
    // buildDrawList() below may need (glTF's own "primitive.material is
    // OPTIONAL -- use the default material when absent" rule -- see that
    // function's own comment). At most ONE extra binding is ever needed
    // regardless of how many material-less submeshes exist: every such
    // submesh resolves to the SAME fallback MaterialHandle, and
    // buildDrawList()'s own materialHandleToBinding lookup memoizes it
    // after the first bind.
    if (!createMaterialParamArena(*app, static_cast<uint32_t>(result.materials.size()) + 1)) {
        destroyApp(*app);
        return 1;
    }
    if (!setupMaterials(*app, *app->registry, result.materials, args->perturbRoughness)) {
        destroyApp(*app);
        return 1;
    }
    if (!buildDrawList(*app, *app->registry, result.scene)) {
        destroyApp(*app);
        return 1;
    }
    // [camera_fit.h's own accumulateReferenceStyleSceneExtents() header
    // comment -- load-bearing, not a plain tight union] PER-PRIMITIVE
    // (submesh) world bounds, exactly the granularity the reference
    // renderer's own getSceneExtents() operates at.
    std::vector<rx::asset::AABB> perPrimitiveWorldBounds;
    for (const rx::asset::InstanceRecord& instance : result.scene.instances) {
        const rx::asset::MeshAsset& mesh = app->registry->mesh(instance.mesh);
        for (const rx::asset::Submesh& submesh : mesh.submeshes) {
            perPrimitiveWorldBounds.push_back(submesh.bounds.transformed(instance.worldTransform));
        }
    }
    const rx::asset::AABB referenceStyleExtents =
        rx::conformance::accumulateReferenceStyleSceneExtents(perPrimitiveWorldBounds);

    const float aspect = static_cast<float>(kRenderWidth) / static_cast<float>(kRenderHeight);
    const rx::conformance::CameraFit fit = rx::conformance::fitCameraToScene(referenceStyleExtents, aspect);

    rx::scene::Camera reversedZCamera;
    reversedZCamera.verticalFovRadians = fit.yfovRadians;
    reversedZCamera.aspectRatio = aspect;
    reversedZCamera.nearPlane = fit.znear;
    reversedZCamera.cullingFarPlane = fit.zfar;
    const glm::mat4 proj = reversedZCamera.cullingProj();
    const glm::mat4 view = glm::lookAt(fit.position, fit.target, glm::vec3(0.0F, 1.0F, 0.0F));
    const glm::mat4 viewProj = proj * view;
    updateDrawDataPerPassFields(*app, viewProj, fit.position);

    VkPhysicalDeviceProperties deviceProps{};
    vkGetPhysicalDeviceProperties(app->device->physicalDevice(), &deviceProps);
    RX_LOG_INFO(
        "rx_conformance_render: model='{}' driver='{}' camera(pos=({:.3f},{:.3f},{:.3f}) "
        "target=({:.3f},{:.3f},{:.3f}) yfov={:.4f} near={:.4f} far={:.4f})",
        model->name, deviceProps.deviceName, fit.position.x, fit.position.y, fit.position.z, fit.target.x,
        fit.target.y, fit.target.z, fit.yfovRadians, fit.znear, fit.zfar);

    rx::graph::RenderGraph graph;
    declareGraph(graph, *app);
    rx::graph::CompileInfo compileInfo;
    compileInfo.swapchainWidth = kRenderWidth;
    compileInfo.swapchainHeight = kRenderHeight;
    compileInfo.swapchainFormat = kBackbufferFormat;
    compileInfo.backbufferFinalLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
    graph.compile(compileInfo);
    app->executor->realize(graph);

    const VkDevice vkDevice = app->device->device();
    VkImage offscreenImage = VK_NULL_HANDLE;
    VkDeviceMemory offscreenMemory = VK_NULL_HANDLE;
    VkImageView offscreenView = VK_NULL_HANDLE;
    auto destroyRawResources = [&]() {
        if (offscreenView != VK_NULL_HANDLE) {
            vkDestroyImageView(vkDevice, offscreenView, nullptr);
        }
        if (offscreenImage != VK_NULL_HANDLE) {
            vkDestroyImage(vkDevice, offscreenImage, nullptr);
        }
        if (offscreenMemory != VK_NULL_HANDLE) {
            vkFreeMemory(vkDevice, offscreenMemory, nullptr);
        }
    };

    VkImageCreateInfo imageInfo{};
    imageInfo.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    imageInfo.imageType = VK_IMAGE_TYPE_2D;
    imageInfo.format = kBackbufferFormat;
    imageInfo.extent = {kRenderWidth, kRenderHeight, 1};
    imageInfo.mipLevels = 1;
    imageInfo.arrayLayers = 1;
    imageInfo.samples = VK_SAMPLE_COUNT_1_BIT;
    imageInfo.tiling = VK_IMAGE_TILING_OPTIMAL;
    imageInfo.usage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT;
    imageInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    imageInfo.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    if (vkCreateImage(vkDevice, &imageInfo, nullptr, &offscreenImage) != VK_SUCCESS) {
        RX_LOG_ERROR("rx_conformance_render: vkCreateImage(offscreen target) failed");
        destroyRawResources();
        destroyApp(*app);
        return 1;
    }
    VkMemoryRequirements memReq{};
    vkGetImageMemoryRequirements(vkDevice, offscreenImage, &memReq);
    VkPhysicalDeviceMemoryProperties memProps{};
    vkGetPhysicalDeviceMemoryProperties(app->device->physicalDevice(), &memProps);
    uint32_t memoryTypeIndex = UINT32_MAX;
    for (uint32_t i = 0; i < memProps.memoryTypeCount; ++i) {
        if ((memReq.memoryTypeBits & (1U << i)) != 0U &&
            (memProps.memoryTypes[i].propertyFlags & VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT) != 0U) {
            memoryTypeIndex = i;
            break;
        }
    }
    if (memoryTypeIndex == UINT32_MAX) {
        RX_LOG_ERROR("rx_conformance_render: no device-local memory type found for the offscreen target");
        destroyRawResources();
        destroyApp(*app);
        return 1;
    }
    VkMemoryAllocateInfo memAllocInfo{};
    memAllocInfo.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    memAllocInfo.allocationSize = memReq.size;
    memAllocInfo.memoryTypeIndex = memoryTypeIndex;
    if (vkAllocateMemory(vkDevice, &memAllocInfo, nullptr, &offscreenMemory) != VK_SUCCESS) {
        RX_LOG_ERROR("rx_conformance_render: vkAllocateMemory(offscreen target) failed");
        destroyRawResources();
        destroyApp(*app);
        return 1;
    }
    if (vkBindImageMemory(vkDevice, offscreenImage, offscreenMemory, 0) != VK_SUCCESS) {
        RX_LOG_ERROR("rx_conformance_render: vkBindImageMemory(offscreen target) failed");
        destroyRawResources();
        destroyApp(*app);
        return 1;
    }
    VkImageViewCreateInfo viewInfo{};
    viewInfo.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    viewInfo.image = offscreenImage;
    viewInfo.viewType = VK_IMAGE_VIEW_TYPE_2D;
    viewInfo.format = kBackbufferFormat;
    viewInfo.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
    viewInfo.subresourceRange.levelCount = 1;
    viewInfo.subresourceRange.layerCount = 1;
    if (vkCreateImageView(vkDevice, &viewInfo, nullptr, &offscreenView) != VK_SUCCESS) {
        RX_LOG_ERROR("rx_conformance_render: vkCreateImageView(offscreen target) failed");
        destroyRawResources();
        destroyApp(*app);
        return 1;
    }

    auto cmdCtx =
        rx::rhi::CommandContext::create(vkDevice, app->device->graphicsQueue(), app->device->graphicsQueueFamily());
    if (!cmdCtx.has_value()) {
        RX_LOG_ERROR("rx_conformance_render: CommandContext::create failed");
        destroyRawResources();
        destroyApp(*app);
        return 1;
    }

    const VkExtent2D extent{kRenderWidth, kRenderHeight};
    cmdCtx->runOnce(
        [&](VkCommandBuffer cmd) { app->executor->execute(graph, cmd, offscreenImage, offscreenView, extent); });

    auto readback = app->allocator->createHostVisibleBuffer(kRenderPixelBytes, VK_BUFFER_USAGE_TRANSFER_DST_BIT);
    bool gateOk = readback.has_value();
    std::vector<uint8_t> pixels;
    if (readback.has_value()) {
        cmdCtx->runOnce([&](VkCommandBuffer cmd) {
            VkBufferImageCopy region{};
            region.imageSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
            region.imageSubresource.layerCount = 1;
            region.imageExtent = {kRenderWidth, kRenderHeight, 1};
            vkCmdCopyImageToBuffer(cmd, offscreenImage, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, readback->handle(), 1,
                                    &region);
        });
        readback->invalidate();
        pixels.resize(static_cast<size_t>(kRenderPixelBytes));
        std::memcpy(pixels.data(), readback->mappedData(), pixels.size());
        gateOk = canonicalizeToRgba8(pixels, kBackbufferFormat);
    } else {
        RX_LOG_ERROR("rx_conformance_render: createHostVisibleBuffer(readback) failed");
    }
    // MUST be destroyed before destroyApp() below tears down the Allocator/
    // Device it was created from -- unlike sample08_gltf_viewer's own
    // captureFrame() lambda (where the equivalent local goes out of scope
    // at the end of EACH lambda call, always before that same sample's own
    // later destroyApp()), this tool renders only once and had no such
    // lambda scope to rely on -- reproduced directly this task as a real
    // "Allocator::destroyAll: torn down with outstanding... allocations"
    // error immediately followed by a segfault at process exit (the same
    // class of teardown-ordering bug this stage's own review history keeps
    // finding -- see sample_08_gltf_viewer's own --quit-during-load comment
    // for the analogous CommandContext-vs-Device lesson).
    readback.reset();

    if (!args->dumpPath.empty() && !pixels.empty()) {
        if (!rx::samples::writeRgba8Png(args->dumpPath, kRenderWidth, kRenderHeight, pixels.data())) {
            RX_LOG_ERROR("rx_conformance_render: --dump '{}' failed to write", args->dumpPath);
        }
    }

    if (gateOk) {
        auto reference = rx::samples::loadRgba8Png(referencePath);
        if (!reference.has_value()) {
            RX_LOG_ERROR("rx_conformance_render: failed to load committed reference '{}'", referencePath.string());
            gateOk = false;
        } else {
            rx::samples::GateResult gate = rx::samples::compareToReference(
                pixels.data(), kRenderWidth, kRenderHeight, reference->rgba8.data(), reference->width,
                reference->height, model->perChannelToleranceOutOf255, model->failingPixelBudgetFraction);
            RX_LOG_INFO(
                "rx_conformance_render: {} gate: driver='{}' failingPixels={}/{} ({:.4f}%) tolerance=+-{}/255 "
                "budget<{:.2f}% pass={}",
                model->name, deviceProps.deviceName, gate.failingPixelCount, gate.totalPixelCount,
                gate.failingPixelFraction * 100.0, model->perChannelToleranceOutOf255,
                model->failingPixelBudgetFraction * 100.0, gate.passed);
            if (!gate.passed) {
                RX_LOG_ERROR(
                    "rx_conformance_render: {} gate FAILED (first mismatch at ({},{}), delta rgba=({},{},{},{}))",
                    model->name, gate.firstMismatchX, gate.firstMismatchY, gate.firstMismatchDelta[0],
                    gate.firstMismatchDelta[1], gate.firstMismatchDelta[2], gate.firstMismatchDelta[3]);
                gateOk = false;
            }
        }
    }

    vkDeviceWaitIdle(vkDevice);
    cmdCtx.reset();
    destroyRawResources();
    destroyApp(*app);

    if (args->validate && app->context->hasValidationErrors()) {
        RX_LOG_ERROR("rx_conformance_render: Vulkan validation layer reported errors during this run");
        gateOk = false;
    }

    if (gateOk) {
        RX_LOG_INFO("rx_conformance_render: {} conformance gate PASSED", model->name);
        return 0;
    }
    RX_LOG_ERROR("rx_conformance_render: {} conformance gate FAILED", model->name);
    return 1;
}
