// rx_ibl/tests/test_ibl_hdr_fixture_gpu.cpp -- Phase 5 Stage 1 Task 9
// [#45, matrix-p5t09-ibl-bake-chain.md file list: "tests (+ tiny
// committed HDR fixtures)"]. Every other test in this suite builds its
// equirect/cube SOURCE via a direct synthetic float upload (this module's
// own `uploadTestSource()` helper) -- correctness-focused and exact, but
// it never exercises the REAL Task 6 HDR decode path
// (rx::asset::decodeStbImageHdr(), the actual function a production
// caller feeds this bake chain through, per this ticket's own "equirect
// HDR (Task 6's loader provides the float input)" scope line). This file
// closes that gap: decodes a tiny, committed, PROCEDURALLY-GENERATED
// Radiance (.hdr) fixture through the real T6 function, uploads the
// DECODED bytes (not a synthetic buffer), and re-runs this suite's own
// uniform-environment exact-conservation check (test_ibl_analytic_gpu.cpp's
// own header comment derives why this is EXACT, not merely converged) --
// an end-to-end integration proof from "real HDR bytes on disk" through
// "real stb decode" to "real baked outputs".
//
// FIXTURE PROVENANCE [Test assets ruling]: data/uniform_test_env.hdr
// (8x4, uniform radiance (0.3, 0.6, 0.9), 159 bytes) was generated by
// this task specifically for this test, via stb_image_write.h's own
// stbi_write_hdr() (the SAME vendored stb release rx_rhi_vk's own
// stb_impl.cpp already links, per that file's own comment -- a
// genuinely zero-new-dependency generator, not sourced from any external
// asset) -- not a real-world photograph/render, so it carries no license
// beyond this repository's own. The one-off generator script itself is
// not committed (a throwaway ~20-line stb_write call, not worth
// preserving as a build target); regenerating an equivalent fixture is
// trivial from this comment's own description if ever needed.
#include "ibl_gpu_fixture.h"

#include <doctest/doctest.h>
#include <rx_asset/texture_decode.h>
#include <rx_ibl/bake.h>

#include <cstddef>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <vector>

using namespace rx::ibl_test;

TEST_CASE("IBL Task 9: real Task 6 HDR decode path (rx::asset::decodeStbImageHdr) feeds a real committed .hdr "
          "fixture into the bake chain -- uniform-environment conservation holds end to end") {
    auto fx = makeIblFixture("rx_ibl_hdr_fixture");
    if (!fx.has_value()) {
        return;
    }

    const std::filesystem::path fixturePath = std::filesystem::path(RX_IBL_TEST_DATA_DIR) / "uniform_test_env.hdr";
    std::ifstream in(fixturePath, std::ios::binary);
    REQUIRE_MESSAGE(in.is_open(), "could not open fixture: ", fixturePath.string());
    std::vector<char> rawBytes((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
    REQUIRE(rawBytes.size() > 0);
    std::vector<std::byte> bytes(rawBytes.size());
    std::memcpy(bytes.data(), rawBytes.data(), rawBytes.size());

    REQUIRE(rx::asset::looksLikeKtx2(bytes) == false);

    std::string failureReason;
    auto decoded = rx::asset::decodeStbImageHdr(bytes, &failureReason);
    REQUIRE_MESSAGE(decoded.has_value(), "decodeStbImageHdr failed: ", failureReason);
    REQUIRE(decoded->width == 8);
    REQUIRE(decoded->height == 4);
    REQUIRE(decoded->rgba32.size() == static_cast<size_t>(8 * 4 * 4));

    // Sanity on the DECODED bytes themselves (before this bake chain ever
    // touches them) -- confirms the fixture round-trips through the real
    // stb decoder at the expected uniform value, so a later failure is
    // attributable to THIS task's own bake math, never a bad fixture.
    for (size_t i = 0; i < decoded->rgba32.size(); i += 4) {
        CHECK(static_cast<double>(decoded->rgba32[i + 0]) == doctest::Approx(0.3).epsilon(0.01));
        CHECK(static_cast<double>(decoded->rgba32[i + 1]) == doctest::Approx(0.6).epsilon(0.01));
        CHECK(static_cast<double>(decoded->rgba32[i + 2]) == doctest::Approx(0.9).epsilon(0.01));
    }

    auto source = uploadTestSource(*fx, decoded->width, decoded->height, 1, decoded->rgba32);
    REQUIRE(source.has_value());

    rx::ibl::BakeParams params;
    params.baseCubemapFaceSize = 32;
    params.irradianceFaceSize = 8;
    params.irradianceSamples = 256;
    params.prefilteredMipCount = 3;
    params.prefilteredBaseFaceSize = 32;
    params.specularSamples = 64;
    params.dfgLutSize = 32;
    params.dfgSamples = 256;

    auto result = rx::ibl::bakeEnvironment(fx->device, fx->allocator, *fx->cmdCtx, *fx->scheduler, *source, false,
                                             RX_IBL_SHADER_DIR, params);
    REQUIRE(result.has_value());

    constexpr double kEps = 0.02;
    for (uint32_t face = 0; face < 6; ++face) {
        auto raw = readbackRaw(*fx, result->irradianceCubemap, 0, face, params.irradianceFaceSize,
                                 params.irradianceFaceSize, 8);
        const uint16_t* half = reinterpret_cast<const uint16_t*>(raw.data());
        size_t center = (static_cast<size_t>(params.irradianceFaceSize / 2) * params.irradianceFaceSize +
                          params.irradianceFaceSize / 2) *
                         4;
        double r = halfToFloat(half[center + 0]);
        double g = halfToFloat(half[center + 1]);
        double b = halfToFloat(half[center + 2]);
        INFO("irradiance face=", face, " rgb=(", r, ",", g, ",", b, ")");
        CHECK(r == doctest::Approx(0.3).epsilon(kEps));
        CHECK(g == doctest::Approx(0.6).epsilon(kEps));
        CHECK(b == doctest::Approx(0.9).epsilon(kEps));
    }

    CHECK_FALSE(fx->context.hasValidationErrors());
}
