#include <doctest/doctest.h>
#include <rx_asset/geometry_pool.h>
#include <rx_asset/registry.h>
#include <rx_rhi_vk/device.h>
#include <rx_rhi_vk/upload.h>
#include <rx_platform/window.h>
#include <rx_task/scheduler.h>
#include <cmath>
#include <filesystem>
#include <memory>
#include <optional>
#include <string>

// draco_compression_test.cpp -- KHR_draco_mesh_compression decode coverage
// [issue #31], additional to import_gltf_gpu_test.cpp's own Task 13
// "decodes within quantization tolerance" test (which this file does not
// duplicate):
//
//   1. Render-equivalence / exact-counter gate: cube_draco.gltf (Draco-
//      compressed) vs. cube_draco_reference.gltf (its uncompressed twin --
//      IDENTICAL positions/normals/uvs/indices/material, generated by the
//      SAME tool -- see tools/gen_gltf_compression_fixtures/main.cpp's own
//      header comment). This is the "full import -> render, with exact-
//      counter/pixel gates" acceptance criterion's counter half; the pixel
//      half is a separate render-level gate driven by
//      sample_08_gltf_viewer against these same two fixtures (see
//      tools/verify_draco_render_gate.sh) rather than duplicated here --
//      this file owns the CPU-side (device-free-shaped, GeometryPool-
//      upload-only) exact-counter proof, matching this codebase's own
//      device-free/GPU-render split precedent
//      (rx_asset_gltf_tests/rx_asset_gltf_gpu_tests vs. the sample
//      binaries' own headless render gates).
//   2. Decode-failure gate: cube_draco_corrupt.gltf (extension present,
//      compressed payload deliberately truncated to 16 bytes) -- must fail
//      cleanly (a named, logged error; the corrupted primitive skipped),
//      never crash, matching this importer's established log-don't-drop
//      discipline for other soft-skippable primitive defects (missing
//      POSITION, non-finite data, zero vertices).
//   3. Real-world Draco asset: BoomBox (glTF-Draco variant), fetched via
//      tools/fetch_assets.sh (mandatory tier, checksummed, gitignored --
//      see that script's own header comment), gracefully skipped when
//      absent, matching damaged_helmet_test.cpp's own convention exactly.
//      CC0-1.0 (Creative Commons Zero) -- Khronos's own canonical
//      KHR_draco_mesh_compression compatibility fixture
//      (extensionsRequired includes it), chosen over an ad hoc Sketchfab
//      download precisely because it is a maintained, stable reference
//      asset with the identical real-world shape (baked PBR textures,
//      TANGENT+NORMAL+TEXCOORD_0+POSITION all Draco-compressed together --
//      the first fixture in this codebase to exercise the TANGENT
//      attribute through decodeDracoPrimitive() at all, since
//      cube_draco.gltf/cube_draco_reference.gltf above carry no TANGENT).

using namespace rx::asset;

namespace {

std::string testAssetDir() { return std::string(RX_ASSET_ROOT_DIR) + "/assets/test"; }
std::string boomBoxDracoPath() { return std::string(RX_ASSET_ROOT_DIR) + "/assets/fetched/BoomBox/glTF-Draco/BoomBox.gltf"; }

// Duplicated from import_gltf_gpu_test.cpp's own GpTestFixture/makeFixture/
// attachPoolAndScheduler -- this codebase's established convention for
// small, canonical GPU test fixtures rather than a cross-TU dependency
// (see test_standard_pbr_unlit.cpp's own header comment on the same
// choice).
struct GpTestFixture {
    rx::platform::Window window;
    rx::rhi::Context context;
    rx::rhi::Device device;
    rx::rhi::Allocator allocator;
    rx::rhi::Uploader uploader;
    std::unique_ptr<rx::asset::GeometryPool> pool;
    std::unique_ptr<rx::task::Scheduler> scheduler;
};

std::optional<GpTestFixture> makeFixture(const char* title) {
    auto window = rx::platform::Window::create(title, 64, 64, /*visible=*/false);
    if (!window.has_value()) {
        MESSAGE("no display backend available, skipping Draco compression test");
        return std::nullopt;
    }
    auto extensions = window->requiredVulkanInstanceExtensions();
    if (extensions.empty()) {
        MESSAGE("video driver reports no Vulkan surface extensions (e.g. dummy driver), skipping Draco compression test");
        return std::nullopt;
    }
    auto context = rx::rhi::Context::create(extensions, /*enableValidation=*/true);
    REQUIRE(context.has_value());
    VkSurfaceKHR surface = window->createVulkanSurface(context->instance());
    REQUIRE(surface != VK_NULL_HANDLE);
    auto device = rx::rhi::Device::create(*context, surface);
    REQUIRE(device.has_value());
    auto allocator = rx::rhi::Allocator::create(*context, *device);
    REQUIRE(allocator.has_value());
    auto uploader = rx::rhi::Uploader::create(*allocator, *device);
    REQUIRE(uploader.has_value());
    // pool/scheduler attached separately below -- see
    // import_gltf_gpu_test.cpp's own makeFixture() header comment for why
    // (reference-capturing members must be constructed against the
    // CALLER's own stable storage, not this function's local temporary).
    return GpTestFixture{std::move(*window), std::move(*context), std::move(*device), std::move(*allocator),
                          std::move(*uploader), nullptr, nullptr};
}

void attachPoolAndScheduler(GpTestFixture& fixture) {
    fixture.pool = rx::asset::GeometryPool::create(fixture.allocator, fixture.device, fixture.uploader);
    fixture.scheduler = rx::task::Scheduler::create(2);
    REQUIRE(fixture.scheduler != nullptr);
}

}  // namespace

TEST_CASE("importGltf: KHR_draco_mesh_compression render-equivalence -- decoded geometry+material match the "
          "uncompressed twin exactly (index count, material) and within Draco's own quantization tolerance (bounds)") {
    auto fixture = makeFixture("draco_render_equivalence");
    if (!fixture) {
        return;
    }
    attachPoolAndScheduler(*fixture);

    Registry compressedRegistry;
    ImportResult compressed = compressedRegistry.importGltf(testAssetDir() + "/cube_draco.gltf", *fixture->pool, *fixture->scheduler);
    REQUIRE(compressed.ok());

    Registry referenceRegistry;
    ImportResult reference =
        referenceRegistry.importGltf(testAssetDir() + "/cube_draco_reference.gltf", *fixture->pool, *fixture->scheduler);
    REQUIRE(reference.ok());

    // -- exact counters --
    REQUIRE(compressed.meshes.size() == 1);
    REQUIRE(reference.meshes.size() == 1);
    REQUIRE(compressed.materials.size() == 1);
    REQUIRE(reference.materials.size() == 1);

    const MeshAsset& compressedMesh = compressedRegistry.mesh(compressed.meshes[0]);
    const MeshAsset& referenceMesh = referenceRegistry.mesh(reference.meshes[0]);
    REQUIRE(compressedMesh.submeshes.size() == 1);
    REQUIRE(referenceMesh.submeshes.size() == 1);
    CHECK(compressedMesh.submeshes[0].range.indexCount == referenceMesh.submeshes[0].range.indexCount);
    CHECK(compressedMesh.submeshes[0].range.indexCount == 6);

    // -- geometry within Draco's own 16-bit position quantization
    // tolerance (identical tolerance to import_gltf_gpu_test.cpp's own
    // decode test) --
    const float tol = 4.0F / 65535.0F;
    CHECK(compressedMesh.bounds.min.x == doctest::Approx(referenceMesh.bounds.min.x).epsilon(tol));
    CHECK(compressedMesh.bounds.min.y == doctest::Approx(referenceMesh.bounds.min.y).epsilon(tol));
    CHECK(compressedMesh.bounds.max.x == doctest::Approx(referenceMesh.bounds.max.x).epsilon(tol));
    CHECK(compressedMesh.bounds.max.y == doctest::Approx(referenceMesh.bounds.max.y).epsilon(tol));

    // -- material: IDENTICAL in both fixtures (materials are never
    // Draco-compressed), so this is an EXACT match, not a tolerance --
    // proves the Draco-compressed primitive's own material reference
    // resolves identically to the uncompressed twin's. --
    const MaterialAsset& compressedMat = compressedRegistry.material(compressed.materials[0]);
    const MaterialAsset& referenceMat = referenceRegistry.material(reference.materials[0]);
    CHECK(compressedMat.disposition == referenceMat.disposition);
    CHECK(compressedMat.baseColorFactor == referenceMat.baseColorFactor);
    CHECK(compressedMat.metallicFactor == referenceMat.metallicFactor);
    CHECK(compressedMat.roughnessFactor == referenceMat.roughnessFactor);

    CHECK_FALSE(fixture->context.hasValidationErrors());
}

TEST_CASE("importGltf: KHR_draco_mesh_compression decode failure (corrupt/truncated compressed payload) fails "
          "cleanly -- named error logged, primitive skipped, no crash, file-level import still completes") {
    auto fixture = makeFixture("draco_decode_failure");
    if (!fixture) {
        return;
    }
    attachPoolAndScheduler(*fixture);

    Registry registry;
    ImportResult result = registry.importGltf(testAssetDir() + "/cube_draco_corrupt.gltf", *fixture->pool, *fixture->scheduler);

    // Matches this importer's established log-don't-drop discipline for a
    // per-primitive defect (identical structural outcome to a primitive
    // missing POSITION, or one rejected for non-finite position data):
    // the FILE-level import still completes successfully (no crash, no
    // hard top-level error) -- the corrupted primitive itself contributes
    // zero geometry instead of aborting the whole import.
    // decodeDracoPrimitive() (import_gltf.cpp) logs a specific
    // RX_LOG_ERROR ("Draco decode failed: ...", carrying Draco's own
    // status message) immediately before returning -- observed directly
    // in this test binary's own captured run output (quoted verbatim in
    // this round's own report; this project has no log-capturing test
    // sink -- Task 13's own report notes the identical limitation for
    // `extras` logging), so this assertion battery proves the STRUCTURAL
    // outcome (mesh registered, zero submeshes, invalid bounds, no crash)
    // rather than re-deriving the log text itself.
    REQUIRE(result.ok());
    REQUIRE(result.meshes.size() == 1);
    const MeshAsset& mesh = registry.mesh(result.meshes[0]);
    CHECK(mesh.submeshes.empty());
    CHECK_FALSE(mesh.bounds.isValid());

    CHECK_FALSE(fixture->context.hasValidationErrors());
}

TEST_CASE("importGltf: BoomBox (fetched, real-world KHR_draco_mesh_compression asset) integration") {
    if (!std::filesystem::exists(boomBoxDracoPath())) {
        MESSAGE("BoomBox glTF-Draco not fetched (run tools/fetch_assets.sh) -- skipping integration test");
        return;
    }

    auto fixture = makeFixture("boombox_draco");
    if (!fixture) {
        return;
    }
    attachPoolAndScheduler(*fixture);

    Registry registry;
    ImportResult result = registry.importGltf(boomBoxDracoPath(), *fixture->pool, *fixture->scheduler);
    REQUIRE(result.ok());

    REQUIRE(result.meshes.size() == 1);
    const MeshAsset& mesh = registry.mesh(result.meshes[0]);
    REQUIRE(mesh.submeshes.size() == 1);

    const Submesh& sub = mesh.submeshes[0];
    // Source index accessor (accessors[0]: {"type":"SCALAR",
    // "componentType":5123,"count":18108}, verified directly against
    // BoomBox.gltf) is u16, decoded via Draco then widened to u32 by the
    // accessor-tools pipeline -- this asserts the WHOLE real-world file's
    // index count survived Draco decode intact.
    CHECK(sub.range.indexCount == 18108);
    CHECK(sub.range.indexCount % 3 == 0);
    CHECK(sub.bounds.isValid());

    // [Review round, Medium finding 2] Decoded-VALUE assertion, not just a
    // structural isValid() check -- BoomBox.gltf's own POSITION accessor
    // (index 4) declares min/max per glTF's own spec requirement (mandatory
    // for POSITION even under Draco compression -- the exporter that wrote
    // this file already computed it from the SAME real decoded data this
    // importer is expected to reproduce), verified directly against the
    // fetched file:
    //   min = (-0.00993099889037616, -0.00978147489037616, -0.01008609019037616)
    //   max = ( 0.009926144998339033, 0.009780322287054225, 0.01008609019037616)
    // An independent ground truth this project never computed itself --
    // catching exactly the class of silent decode corruption a corrupted-
    // but-still-"successful" decode can produce (right COUNTS, wrong
    // VALUES) that the index-count check alone would miss. Cross-checked
    // independently a second way while investigating this review round's
    // findings: Draco's OWN reference `draco_decoder` CLI (a standalone
    // binary this project's own dep-cache sub-build already produces,
    // entirely independent of this importer's own code), run directly
    // against the extracted compressed bufferView bytes, decodes the
    // SAME tiny (~0.01) magnitude values -- not the ~1.0 magnitude this
    // review round's investigation found this importer itself producing
    // before the GetAttributeByUniqueId() fix a few lines above (a real,
    // separate, pre-existing bug this decoded-value assertion class
    // exists specifically to catch: `mesh->attribute(i)`'s ARRAY index
    // does not equal the Draco attribute's persistent unique_id() after
    // decode for real-world content, so the previous array-index lookup
    // was silently reading NORMAL data (a similarly-shaped but semantically
    // wrong VEC3 attribute, unit-vector-scaled -- explaining the
    // ~[-1,1] result observed) into the POSITION output). A plain
    // absolute-margin check (this project's vendored doctest only exposes
    // Approx::epsilon()/scale(), a RELATIVE tolerance -- see
    // test_standard_pbr_unlit.cpp's own near8() for the identical
    // reasoning) at 0.0005 -- roughly 50x the actual observed decode
    // deviation (~0.00001, Draco's own quantization step for whatever
    // bit-depth this asset's external encoder used) and roughly 2000x
    // tighter than the ~1.0 deviation the real bug this test caught
    // produced, so this is tight enough to fail hard on a real decode
    // defect while remaining robust to ordinary quantization noise.
    const auto nearAbs = [](float actual, double expected, float margin) { return std::abs(actual - static_cast<float>(expected)) < margin; };
    CHECK(nearAbs(sub.bounds.min.x, -0.00993099889037616, 0.0005F));
    CHECK(nearAbs(sub.bounds.min.y, -0.00978147489037616, 0.0005F));
    CHECK(nearAbs(sub.bounds.min.z, -0.01008609019037616, 0.0005F));
    CHECK(nearAbs(sub.bounds.max.x, 0.009926144998339033, 0.0005F));
    CHECK(nearAbs(sub.bounds.max.y, 0.009780322287054225, 0.0005F));
    CHECK(nearAbs(sub.bounds.max.z, 0.01008609019037616, 0.0005F));

    // BoomBox has no skin in the source file -- asserting `present ==
    // false` (rather than omitting the check) is itself the proof this
    // importer does not fabricate skin data for an unskinned asset,
    // matching damaged_helmet_test.cpp's own identical assertion.
    CHECK_FALSE(mesh.skin.present);

    REQUIRE(result.materials.size() == 1);
    const MaterialAsset& material = registry.material(result.materials[0]);
    CHECK(material.name == "BoomBox_Mat");
    CHECK(material.disposition == MaterialDisposition::StandardPBR);
    CHECK(material.baseColorTexture.present);
    CHECK(material.metallicRoughnessTexture.present);
    CHECK(material.normalTexture.present);
    CHECK(material.occlusionTexture.present);
    CHECK(material.emissiveTexture.present);

    CHECK(result.scene.instances.size() == 1);

    CHECK_FALSE(fixture->context.hasValidationErrors());
}
