# Builds a CMake-based dependency exactly once per (name, pin, target
# triple, zig version, CMAKE_ARGS, CMAKE_BUILD_TYPE, and toolchain/wrapper config)
# and reuses the cached install on every later configure. A cache hit costs zero compilation.
#
# Cache key format: SHA256(name|tag|triple|zig-version|build-type|length-prefixed CMAKE_ARGS|length-prefixed file-hashes)
# CMAKE_ARGS and file hashes are encoded as "<len>:<arg>" or "<len>:<hash>" per element
# (length-prefixing ensures distinct keys for distinct argument lists or config changes,
# regardless of delimiter characters). File hashes cover cmake/DepCache.cmake, toolchains/*,
# and zig-wrappers/* to detect configuration changes at the source.
# Truncated to 16 hex chars, then prefixed with name: "name-<hash>". Changing any input
# (CMAKE_ARGS, CMAKE_BUILD_TYPE, toolchain, or zig wrapper) invalidates the key and forces
# a rebuild.
#
# Side effect [closure-sweep item 5 minor]: every rx_add_cached_dependency()
# call also appends its own resolved key to
# ${CMAKE_BINARY_DIR}/deps-cache-manifest.txt (fresh per configure, never
# itself cached) -- the authoritative "currently referenced" list ci.yml's
# own prune-stale-cache-entries step reads before saving the .deps-cache/
# actions/cache entry, so an actions/cache restore-keys fallback (which can
# carry forward older, no-longer-referenced hash-keyed subdirectories) does
# not make that cache grow unbounded over time.

function(rx_dep_cache_key OUT_VAR NAME TAG CMAKE_ARGS_LIST)
  execute_process(
    COMMAND "${CMAKE_SOURCE_DIR}/toolchain/zig/zig" version
    OUTPUT_VARIABLE _zig_version
    OUTPUT_STRIP_TRAILING_WHITESPACE)

  # Encode CMAKE_ARGS with length-prefixing
  set(_cmake_args_encoded "")
  foreach(_arg ${CMAKE_ARGS_LIST})
    string(LENGTH "${_arg}" _arg_len)
    string(APPEND _cmake_args_encoded "${_arg_len}:${_arg}")
  endforeach()

  # Hash configuration files that affect the build: DepCache.cmake itself,
  # toolchain files, and zig wrapper scripts
  set(_config_files_encoded "")

  # DepCache.cmake
  file(SHA256 "${CMAKE_SOURCE_DIR}/cmake/DepCache.cmake" _depcache_hash)
  string(LENGTH "${_depcache_hash}" _len)
  string(APPEND _config_files_encoded "${_len}:${_depcache_hash}")

  # Current toolchain file (the one actually being used)
  file(SHA256 "${CMAKE_TOOLCHAIN_FILE}" _toolchain_hash)
  string(LENGTH "${_toolchain_hash}" _len)
  string(APPEND _config_files_encoded "${_len}:${_toolchain_hash}")

  # All zig-wrapper scripts (in case any are modified)
  file(GLOB _zig_wrappers "${CMAKE_SOURCE_DIR}/cmake/zig-wrappers/*")
  list(SORT _zig_wrappers)
  foreach(_wrapper ${_zig_wrappers})
    file(SHA256 "${_wrapper}" _wrapper_hash)
    string(LENGTH "${_wrapper_hash}" _len)
    string(APPEND _config_files_encoded "${_len}:${_wrapper_hash}")
  endforeach()

  string(SHA256 _hash "${NAME}|${TAG}|${RX_TARGET_TRIPLE}|${_zig_version}|${CMAKE_BUILD_TYPE}|${_cmake_args_encoded}|${_config_files_encoded}")
  string(SUBSTRING "${_hash}" 0 16 _hash)
  set(${OUT_VAR} "${NAME}-${_hash}" PARENT_SCOPE)
endfunction()

function(rx_add_cached_dependency)
  set(oneValueArgs NAME REPO TAG)
  set(multiValueArgs CMAKE_ARGS)
  cmake_parse_arguments(DEP "" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  rx_dep_cache_key(_key ${DEP_NAME} ${DEP_TAG} "${DEP_CMAKE_ARGS}")
  set(_cache_dir "${CMAKE_SOURCE_DIR}/.deps-cache/${_key}")
  set(_marker "${_cache_dir}/.rx-built")

  # [closure-sweep item 5 minor] CI's restore-keys prefix fallback (added
  # for the deps-cache actions/cache step, ci.yml) means a restored cache
  # can carry forward hash-keyed subdirectories from an OLDER configure
  # that the CURRENT one no longer references at all (a removed
  # dependency, a re-pinned tag, a changed CMAKE_ARGS/toolchain hash) --
  # nothing else ever deletes them, so the cache would otherwise grow
  # monotonically across edits. Record every key THIS configure actually
  # references (build-dir-local, never itself cached/restored, so it is
  # always freshly and completely regenerated by a real configure) so
  # ci.yml's own prune step (run right after Configure, before the
  # cache-save) has an authoritative, safe "keep" list: by the time this
  # function returns without a FATAL_ERROR below, ${_key} genuinely IS
  # built and installed, so anything NOT in this manifest by the end of
  # configure is provably safe to delete.
  get_property(_rx_deps_manifest_initialized GLOBAL PROPERTY RX_DEPS_CACHE_MANIFEST_INIT)
  if(NOT _rx_deps_manifest_initialized)
    file(WRITE "${CMAKE_BINARY_DIR}/deps-cache-manifest.txt" "")
    set_property(GLOBAL PROPERTY RX_DEPS_CACHE_MANIFEST_INIT TRUE)
  endif()
  file(APPEND "${CMAKE_BINARY_DIR}/deps-cache-manifest.txt" "${_key}\n")

  if(NOT EXISTS "${_marker}")
    message(STATUS "[dep-cache] MISS for ${DEP_NAME} (key=${_key}) - building once")

    set(_src_dir "${CMAKE_BINARY_DIR}/_deps-src/${DEP_NAME}")
    if(NOT EXISTS "${_src_dir}/.git")
      execute_process(COMMAND git clone --quiet "${DEP_REPO}" "${_src_dir}" RESULT_VARIABLE _rv)
      if(NOT _rv EQUAL 0)
        message(FATAL_ERROR "[dep-cache] git clone failed for ${DEP_NAME} (${DEP_REPO})")
      endif()
    endif()

    execute_process(COMMAND git -C "${_src_dir}" fetch --quiet --depth 1 origin "${DEP_TAG}" RESULT_VARIABLE _rv)
    if(NOT _rv EQUAL 0)
      message(FATAL_ERROR "[dep-cache] git fetch of pin '${DEP_TAG}' failed for ${DEP_NAME}")
    endif()

    execute_process(COMMAND git -C "${_src_dir}" checkout --quiet FETCH_HEAD RESULT_VARIABLE _rv)
    if(NOT _rv EQUAL 0)
      message(FATAL_ERROR "[dep-cache] git checkout of pin '${DEP_TAG}' failed for ${DEP_NAME}")
    endif()

    set(_build_dir "${CMAKE_BINARY_DIR}/_deps-build/${DEP_NAME}")
    execute_process(
      COMMAND "${CMAKE_COMMAND}" -S "${_src_dir}" -B "${_build_dir}" -G "${CMAKE_GENERATOR}"
              "-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}"
              "-DCMAKE_INSTALL_PREFIX=${_cache_dir}"
              "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
              ${DEP_CMAKE_ARGS}
      RESULT_VARIABLE _rv)
    if(NOT _rv EQUAL 0)
      message(FATAL_ERROR "[dep-cache] configure failed for ${DEP_NAME} - see output above")
    endif()

    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build_dir}" --target install RESULT_VARIABLE _rv)
    if(NOT _rv EQUAL 0)
      message(FATAL_ERROR "[dep-cache] build/install failed for ${DEP_NAME} - see output above")
    endif()

    file(WRITE "${_marker}" "${DEP_TAG}\n")
  else()
    message(STATUS "[dep-cache] HIT for ${DEP_NAME} (key=${_key}) - reusing cached install, no compilation")
  endif()

  set(${DEP_NAME}_CACHE_DIR "${_cache_dir}" PARENT_SCOPE)
  set(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH};${_cache_dir}" PARENT_SCOPE)
endfunction()
